package discord.gamesdk;// Generated by jextract

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct DiscordActivityAssets {
 *     char large_image[128];
 *     char large_text[128];
 *     char small_image[128];
 *     char small_text[128];
 * }
 * }
 */
public class DiscordActivityAssets {

    DiscordActivityAssets() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(128, discord_game_sdk_h.C_CHAR).withName("large_image"),
        MemoryLayout.sequenceLayout(128, discord_game_sdk_h.C_CHAR).withName("large_text"),
        MemoryLayout.sequenceLayout(128, discord_game_sdk_h.C_CHAR).withName("small_image"),
        MemoryLayout.sequenceLayout(128, discord_game_sdk_h.C_CHAR).withName("small_text")
    ).withName("DiscordActivityAssets");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final SequenceLayout large_image$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("large_image"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char large_image[128]
     * }
     */
    public static final SequenceLayout large_image$layout() {
        return large_image$LAYOUT;
    }

    private static final long large_image$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char large_image[128]
     * }
     */
    public static final long large_image$offset() {
        return large_image$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char large_image[128]
     * }
     */
    public static MemorySegment large_image(MemorySegment struct) {
        return struct.asSlice(large_image$OFFSET, large_image$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char large_image[128]
     * }
     */
    public static void large_image(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, large_image$OFFSET, large_image$LAYOUT.byteSize());
    }

    private static long[] large_image$DIMS = { 128 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char large_image[128]
     * }
     */
    public static long[] large_image$dimensions() {
        return large_image$DIMS;
    }
    private static final VarHandle large_image$ELEM_HANDLE = large_image$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char large_image[128]
     * }
     */
    public static byte large_image(MemorySegment struct, long index0) {
        return (byte)large_image$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char large_image[128]
     * }
     */
    public static void large_image(MemorySegment struct, long index0, byte fieldValue) {
        large_image$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final SequenceLayout large_text$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("large_text"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char large_text[128]
     * }
     */
    public static final SequenceLayout large_text$layout() {
        return large_text$LAYOUT;
    }

    private static final long large_text$OFFSET = 128;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char large_text[128]
     * }
     */
    public static final long large_text$offset() {
        return large_text$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char large_text[128]
     * }
     */
    public static MemorySegment large_text(MemorySegment struct) {
        return struct.asSlice(large_text$OFFSET, large_text$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char large_text[128]
     * }
     */
    public static void large_text(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, large_text$OFFSET, large_text$LAYOUT.byteSize());
    }

    private static long[] large_text$DIMS = { 128 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char large_text[128]
     * }
     */
    public static long[] large_text$dimensions() {
        return large_text$DIMS;
    }
    private static final VarHandle large_text$ELEM_HANDLE = large_text$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char large_text[128]
     * }
     */
    public static byte large_text(MemorySegment struct, long index0) {
        return (byte)large_text$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char large_text[128]
     * }
     */
    public static void large_text(MemorySegment struct, long index0, byte fieldValue) {
        large_text$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final SequenceLayout small_image$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("small_image"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char small_image[128]
     * }
     */
    public static final SequenceLayout small_image$layout() {
        return small_image$LAYOUT;
    }

    private static final long small_image$OFFSET = 256;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char small_image[128]
     * }
     */
    public static final long small_image$offset() {
        return small_image$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char small_image[128]
     * }
     */
    public static MemorySegment small_image(MemorySegment struct) {
        return struct.asSlice(small_image$OFFSET, small_image$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char small_image[128]
     * }
     */
    public static void small_image(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, small_image$OFFSET, small_image$LAYOUT.byteSize());
    }

    private static long[] small_image$DIMS = { 128 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char small_image[128]
     * }
     */
    public static long[] small_image$dimensions() {
        return small_image$DIMS;
    }
    private static final VarHandle small_image$ELEM_HANDLE = small_image$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char small_image[128]
     * }
     */
    public static byte small_image(MemorySegment struct, long index0) {
        return (byte)small_image$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char small_image[128]
     * }
     */
    public static void small_image(MemorySegment struct, long index0, byte fieldValue) {
        small_image$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final SequenceLayout small_text$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("small_text"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char small_text[128]
     * }
     */
    public static final SequenceLayout small_text$layout() {
        return small_text$LAYOUT;
    }

    private static final long small_text$OFFSET = 384;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char small_text[128]
     * }
     */
    public static final long small_text$offset() {
        return small_text$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char small_text[128]
     * }
     */
    public static MemorySegment small_text(MemorySegment struct) {
        return struct.asSlice(small_text$OFFSET, small_text$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char small_text[128]
     * }
     */
    public static void small_text(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, small_text$OFFSET, small_text$LAYOUT.byteSize());
    }

    private static long[] small_text$DIMS = { 128 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char small_text[128]
     * }
     */
    public static long[] small_text$dimensions() {
        return small_text$DIMS;
    }
    private static final VarHandle small_text$ELEM_HANDLE = small_text$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char small_text[128]
     * }
     */
    public static byte small_text(MemorySegment struct, long index0) {
        return (byte)small_text$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char small_text[128]
     * }
     */
    public static void small_text(MemorySegment struct, long index0, byte fieldValue) {
        small_text$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

