package discord.gamesdk;// Generated by jextract

import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct DiscordRelationship {
 *     enum EDiscordRelationshipType type;
 *     struct DiscordUser user;
 *     struct DiscordPresence presence;
 * }
 * }
 */
public class DiscordRelationship {

    DiscordRelationship() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        discord_game_sdk_h.C_INT.withName("type"),
        MemoryLayout.paddingLayout(4),
        DiscordUser.layout().withName("user"),
        DiscordPresence.layout().withName("presence")
    ).withName("DiscordRelationship");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum EDiscordRelationshipType type
     * }
     */
    public static final OfInt type$layout() {
        return type$LAYOUT;
    }

    private static final long type$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum EDiscordRelationshipType type
     * }
     */
    public static final long type$offset() {
        return type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum EDiscordRelationshipType type
     * }
     */
    public static int type(MemorySegment struct) {
        return struct.get(type$LAYOUT, type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum EDiscordRelationshipType type
     * }
     */
    public static void type(MemorySegment struct, int fieldValue) {
        struct.set(type$LAYOUT, type$OFFSET, fieldValue);
    }

    private static final GroupLayout user$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("user"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct DiscordUser user
     * }
     */
    public static final GroupLayout user$layout() {
        return user$LAYOUT;
    }

    private static final long user$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct DiscordUser user
     * }
     */
    public static final long user$offset() {
        return user$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct DiscordUser user
     * }
     */
    public static MemorySegment user(MemorySegment struct) {
        return struct.asSlice(user$OFFSET, user$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct DiscordUser user
     * }
     */
    public static void user(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, user$OFFSET, user$LAYOUT.byteSize());
    }

    private static final GroupLayout presence$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("presence"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct DiscordPresence presence
     * }
     */
    public static final GroupLayout presence$layout() {
        return presence$LAYOUT;
    }

    private static final long presence$OFFSET = 416;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct DiscordPresence presence
     * }
     */
    public static final long presence$offset() {
        return presence$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct DiscordPresence presence
     * }
     */
    public static MemorySegment presence(MemorySegment struct) {
        return struct.asSlice(presence$OFFSET, presence$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct DiscordPresence presence
     * }
     */
    public static void presence(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, presence$OFFSET, presence$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

