package discord.gamesdk;// Generated by jextract

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct DiscordOAuth2Token {
 *     char access_token[128];
 *     char scopes[1024];
 *     DiscordTimestamp expires;
 * }
 * }
 */
public class DiscordOAuth2Token {

    DiscordOAuth2Token() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(128, discord_game_sdk_h.C_CHAR).withName("access_token"),
        MemoryLayout.sequenceLayout(1024, discord_game_sdk_h.C_CHAR).withName("scopes"),
        discord_game_sdk_h.C_LONG_LONG.withName("expires")
    ).withName("DiscordOAuth2Token");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final SequenceLayout access_token$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("access_token"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char access_token[128]
     * }
     */
    public static final SequenceLayout access_token$layout() {
        return access_token$LAYOUT;
    }

    private static final long access_token$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char access_token[128]
     * }
     */
    public static final long access_token$offset() {
        return access_token$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char access_token[128]
     * }
     */
    public static MemorySegment access_token(MemorySegment struct) {
        return struct.asSlice(access_token$OFFSET, access_token$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char access_token[128]
     * }
     */
    public static void access_token(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, access_token$OFFSET, access_token$LAYOUT.byteSize());
    }

    private static long[] access_token$DIMS = { 128 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char access_token[128]
     * }
     */
    public static long[] access_token$dimensions() {
        return access_token$DIMS;
    }
    private static final VarHandle access_token$ELEM_HANDLE = access_token$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char access_token[128]
     * }
     */
    public static byte access_token(MemorySegment struct, long index0) {
        return (byte)access_token$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char access_token[128]
     * }
     */
    public static void access_token(MemorySegment struct, long index0, byte fieldValue) {
        access_token$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final SequenceLayout scopes$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("scopes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char scopes[1024]
     * }
     */
    public static final SequenceLayout scopes$layout() {
        return scopes$LAYOUT;
    }

    private static final long scopes$OFFSET = 128;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char scopes[1024]
     * }
     */
    public static final long scopes$offset() {
        return scopes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char scopes[1024]
     * }
     */
    public static MemorySegment scopes(MemorySegment struct) {
        return struct.asSlice(scopes$OFFSET, scopes$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char scopes[1024]
     * }
     */
    public static void scopes(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, scopes$OFFSET, scopes$LAYOUT.byteSize());
    }

    private static long[] scopes$DIMS = { 1024 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char scopes[1024]
     * }
     */
    public static long[] scopes$dimensions() {
        return scopes$DIMS;
    }
    private static final VarHandle scopes$ELEM_HANDLE = scopes$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char scopes[1024]
     * }
     */
    public static byte scopes(MemorySegment struct, long index0) {
        return (byte)scopes$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char scopes[1024]
     * }
     */
    public static void scopes(MemorySegment struct, long index0, byte fieldValue) {
        scopes$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final OfLong expires$LAYOUT = (OfLong)$LAYOUT.select(groupElement("expires"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DiscordTimestamp expires
     * }
     */
    public static final OfLong expires$layout() {
        return expires$LAYOUT;
    }

    private static final long expires$OFFSET = 1152;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DiscordTimestamp expires
     * }
     */
    public static final long expires$offset() {
        return expires$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DiscordTimestamp expires
     * }
     */
    public static long expires(MemorySegment struct) {
        return struct.get(expires$LAYOUT, expires$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DiscordTimestamp expires
     * }
     */
    public static void expires(MemorySegment struct, long fieldValue) {
        struct.set(expires$LAYOUT, expires$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

