package discord.gamesdk;// Generated by jextract

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct DiscordActivityParty {
 *     char id[128];
 *     struct DiscordPartySize size;
 *     enum EDiscordActivityPartyPrivacy privacy;
 * }
 * }
 */
public class DiscordActivityParty {

    DiscordActivityParty() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(128, discord_game_sdk_h.C_CHAR).withName("id"),
        DiscordPartySize.layout().withName("size"),
        discord_game_sdk_h.C_INT.withName("privacy")
    ).withName("DiscordActivityParty");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final SequenceLayout id$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char id[128]
     * }
     */
    public static final SequenceLayout id$layout() {
        return id$LAYOUT;
    }

    private static final long id$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char id[128]
     * }
     */
    public static final long id$offset() {
        return id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char id[128]
     * }
     */
    public static MemorySegment id(MemorySegment struct) {
        return struct.asSlice(id$OFFSET, id$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char id[128]
     * }
     */
    public static void id(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, id$OFFSET, id$LAYOUT.byteSize());
    }

    private static long[] id$DIMS = { 128 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char id[128]
     * }
     */
    public static long[] id$dimensions() {
        return id$DIMS;
    }
    private static final VarHandle id$ELEM_HANDLE = id$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char id[128]
     * }
     */
    public static byte id(MemorySegment struct, long index0) {
        return (byte)id$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char id[128]
     * }
     */
    public static void id(MemorySegment struct, long index0, byte fieldValue) {
        id$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final GroupLayout size$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct DiscordPartySize size
     * }
     */
    public static final GroupLayout size$layout() {
        return size$LAYOUT;
    }

    private static final long size$OFFSET = 128;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct DiscordPartySize size
     * }
     */
    public static final long size$offset() {
        return size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct DiscordPartySize size
     * }
     */
    public static MemorySegment size(MemorySegment struct) {
        return struct.asSlice(size$OFFSET, size$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct DiscordPartySize size
     * }
     */
    public static void size(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, size$OFFSET, size$LAYOUT.byteSize());
    }

    private static final OfInt privacy$LAYOUT = (OfInt)$LAYOUT.select(groupElement("privacy"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum EDiscordActivityPartyPrivacy privacy
     * }
     */
    public static final OfInt privacy$layout() {
        return privacy$LAYOUT;
    }

    private static final long privacy$OFFSET = 136;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum EDiscordActivityPartyPrivacy privacy
     * }
     */
    public static final long privacy$offset() {
        return privacy$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum EDiscordActivityPartyPrivacy privacy
     * }
     */
    public static int privacy(MemorySegment struct) {
        return struct.get(privacy$LAYOUT, privacy$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum EDiscordActivityPartyPrivacy privacy
     * }
     */
    public static void privacy(MemorySegment struct, int fieldValue) {
        struct.set(privacy$LAYOUT, privacy$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

