package discord.gamesdk;// Generated by jextract

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct DiscordInputMode {
 *     enum EDiscordInputModeType type;
 *     char shortcut[256];
 * }
 * }
 */
public class DiscordInputMode {

    DiscordInputMode() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        discord_game_sdk_h.C_INT.withName("type"),
        MemoryLayout.sequenceLayout(256, discord_game_sdk_h.C_CHAR).withName("shortcut")
    ).withName("DiscordInputMode");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum EDiscordInputModeType type
     * }
     */
    public static final OfInt type$layout() {
        return type$LAYOUT;
    }

    private static final long type$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum EDiscordInputModeType type
     * }
     */
    public static final long type$offset() {
        return type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum EDiscordInputModeType type
     * }
     */
    public static int type(MemorySegment struct) {
        return struct.get(type$LAYOUT, type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum EDiscordInputModeType type
     * }
     */
    public static void type(MemorySegment struct, int fieldValue) {
        struct.set(type$LAYOUT, type$OFFSET, fieldValue);
    }

    private static final SequenceLayout shortcut$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("shortcut"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char shortcut[256]
     * }
     */
    public static final SequenceLayout shortcut$layout() {
        return shortcut$LAYOUT;
    }

    private static final long shortcut$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char shortcut[256]
     * }
     */
    public static final long shortcut$offset() {
        return shortcut$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char shortcut[256]
     * }
     */
    public static MemorySegment shortcut(MemorySegment struct) {
        return struct.asSlice(shortcut$OFFSET, shortcut$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char shortcut[256]
     * }
     */
    public static void shortcut(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, shortcut$OFFSET, shortcut$LAYOUT.byteSize());
    }

    private static long[] shortcut$DIMS = { 256 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char shortcut[256]
     * }
     */
    public static long[] shortcut$dimensions() {
        return shortcut$DIMS;
    }
    private static final VarHandle shortcut$ELEM_HANDLE = shortcut$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char shortcut[256]
     * }
     */
    public static byte shortcut(MemorySegment struct, long index0) {
        return (byte)shortcut$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char shortcut[256]
     * }
     */
    public static void shortcut(MemorySegment struct, long index0, byte fieldValue) {
        shortcut$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

