package discord.gamesdk;// Generated by jextract

import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct DiscordEntitlement {
 *     DiscordSnowflake id;
 *     enum EDiscordEntitlementType type;
 *     DiscordSnowflake sku_id;
 * }
 * }
 */
public class DiscordEntitlement {

    DiscordEntitlement() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        discord_game_sdk_h.C_LONG_LONG.withName("id"),
        discord_game_sdk_h.C_INT.withName("type"),
        MemoryLayout.paddingLayout(4),
        discord_game_sdk_h.C_LONG_LONG.withName("sku_id")
    ).withName("DiscordEntitlement");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong id$LAYOUT = (OfLong)$LAYOUT.select(groupElement("id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DiscordSnowflake id
     * }
     */
    public static final OfLong id$layout() {
        return id$LAYOUT;
    }

    private static final long id$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DiscordSnowflake id
     * }
     */
    public static final long id$offset() {
        return id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DiscordSnowflake id
     * }
     */
    public static long id(MemorySegment struct) {
        return struct.get(id$LAYOUT, id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DiscordSnowflake id
     * }
     */
    public static void id(MemorySegment struct, long fieldValue) {
        struct.set(id$LAYOUT, id$OFFSET, fieldValue);
    }

    private static final OfInt type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum EDiscordEntitlementType type
     * }
     */
    public static final OfInt type$layout() {
        return type$LAYOUT;
    }

    private static final long type$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum EDiscordEntitlementType type
     * }
     */
    public static final long type$offset() {
        return type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum EDiscordEntitlementType type
     * }
     */
    public static int type(MemorySegment struct) {
        return struct.get(type$LAYOUT, type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum EDiscordEntitlementType type
     * }
     */
    public static void type(MemorySegment struct, int fieldValue) {
        struct.set(type$LAYOUT, type$OFFSET, fieldValue);
    }

    private static final OfLong sku_id$LAYOUT = (OfLong)$LAYOUT.select(groupElement("sku_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DiscordSnowflake sku_id
     * }
     */
    public static final OfLong sku_id$layout() {
        return sku_id$LAYOUT;
    }

    private static final long sku_id$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DiscordSnowflake sku_id
     * }
     */
    public static final long sku_id$offset() {
        return sku_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DiscordSnowflake sku_id
     * }
     */
    public static long sku_id(MemorySegment struct) {
        return struct.get(sku_id$LAYOUT, sku_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DiscordSnowflake sku_id
     * }
     */
    public static void sku_id(MemorySegment struct, long fieldValue) {
        struct.set(sku_id$LAYOUT, sku_id$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

