package discord.gamesdk;// Generated by jextract

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct DiscordActivitySecrets {
 *     char match[128];
 *     char join[128];
 *     char spectate[128];
 * }
 * }
 */
public class DiscordActivitySecrets {

    DiscordActivitySecrets() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(128, discord_game_sdk_h.C_CHAR).withName("match"),
        MemoryLayout.sequenceLayout(128, discord_game_sdk_h.C_CHAR).withName("join"),
        MemoryLayout.sequenceLayout(128, discord_game_sdk_h.C_CHAR).withName("spectate")
    ).withName("DiscordActivitySecrets");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final SequenceLayout match$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("match"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char match[128]
     * }
     */
    public static final SequenceLayout match$layout() {
        return match$LAYOUT;
    }

    private static final long match$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char match[128]
     * }
     */
    public static final long match$offset() {
        return match$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char match[128]
     * }
     */
    public static MemorySegment match(MemorySegment struct) {
        return struct.asSlice(match$OFFSET, match$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char match[128]
     * }
     */
    public static void match(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, match$OFFSET, match$LAYOUT.byteSize());
    }

    private static long[] match$DIMS = { 128 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char match[128]
     * }
     */
    public static long[] match$dimensions() {
        return match$DIMS;
    }
    private static final VarHandle match$ELEM_HANDLE = match$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char match[128]
     * }
     */
    public static byte match(MemorySegment struct, long index0) {
        return (byte)match$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char match[128]
     * }
     */
    public static void match(MemorySegment struct, long index0, byte fieldValue) {
        match$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final SequenceLayout join$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("join"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char join[128]
     * }
     */
    public static final SequenceLayout join$layout() {
        return join$LAYOUT;
    }

    private static final long join$OFFSET = 128;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char join[128]
     * }
     */
    public static final long join$offset() {
        return join$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char join[128]
     * }
     */
    public static MemorySegment join(MemorySegment struct) {
        return struct.asSlice(join$OFFSET, join$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char join[128]
     * }
     */
    public static void join(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, join$OFFSET, join$LAYOUT.byteSize());
    }

    private static long[] join$DIMS = { 128 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char join[128]
     * }
     */
    public static long[] join$dimensions() {
        return join$DIMS;
    }
    private static final VarHandle join$ELEM_HANDLE = join$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char join[128]
     * }
     */
    public static byte join(MemorySegment struct, long index0) {
        return (byte)join$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char join[128]
     * }
     */
    public static void join(MemorySegment struct, long index0, byte fieldValue) {
        join$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final SequenceLayout spectate$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("spectate"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char spectate[128]
     * }
     */
    public static final SequenceLayout spectate$layout() {
        return spectate$LAYOUT;
    }

    private static final long spectate$OFFSET = 256;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char spectate[128]
     * }
     */
    public static final long spectate$offset() {
        return spectate$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char spectate[128]
     * }
     */
    public static MemorySegment spectate(MemorySegment struct) {
        return struct.asSlice(spectate$OFFSET, spectate$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char spectate[128]
     * }
     */
    public static void spectate(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, spectate$OFFSET, spectate$LAYOUT.byteSize());
    }

    private static long[] spectate$DIMS = { 128 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char spectate[128]
     * }
     */
    public static long[] spectate$dimensions() {
        return spectate$DIMS;
    }
    private static final VarHandle spectate$ELEM_HANDLE = spectate$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char spectate[128]
     * }
     */
    public static byte spectate(MemorySegment struct, long index0) {
        return (byte)spectate$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char spectate[128]
     * }
     */
    public static void spectate(MemorySegment struct, long index0, byte fieldValue) {
        spectate$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

