package discord.gamesdk;// Generated by jextract

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct IDiscordLobbyEvents {
 *     void (*on_lobby_update)(void *, int64_t);
 *     void (*on_lobby_delete)(void *, int64_t, uint32_t);
 *     void (*on_member_connect)(void *, int64_t, int64_t);
 *     void (*on_member_update)(void *, int64_t, int64_t);
 *     void (*on_member_disconnect)(void *, int64_t, int64_t);
 *     void (*on_lobby_message)(void *, int64_t, int64_t, uint8_t *, uint32_t);
 *     void (*on_speaking)(void *, int64_t, int64_t, bool);
 *     void (*on_network_message)(void *, int64_t, int64_t, uint8_t, uint8_t *, uint32_t);
 * }
 * }
 */
public class IDiscordLobbyEvents {

    IDiscordLobbyEvents() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        discord_game_sdk_h.C_POINTER.withName("on_lobby_update"),
        discord_game_sdk_h.C_POINTER.withName("on_lobby_delete"),
        discord_game_sdk_h.C_POINTER.withName("on_member_connect"),
        discord_game_sdk_h.C_POINTER.withName("on_member_update"),
        discord_game_sdk_h.C_POINTER.withName("on_member_disconnect"),
        discord_game_sdk_h.C_POINTER.withName("on_lobby_message"),
        discord_game_sdk_h.C_POINTER.withName("on_speaking"),
        discord_game_sdk_h.C_POINTER.withName("on_network_message")
    ).withName("IDiscordLobbyEvents");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * {@snippet lang=c :
     * void (*on_lobby_update)(void *, int64_t)
     * }
     */
    public static class on_lobby_update {

        on_lobby_update() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, long _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_LONG_LONG
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr,MemorySegment _x0, long _x1) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout on_lobby_update$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("on_lobby_update"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*on_lobby_update)(void *, int64_t)
     * }
     */
    public static final AddressLayout on_lobby_update$layout() {
        return on_lobby_update$LAYOUT;
    }

    private static final long on_lobby_update$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*on_lobby_update)(void *, int64_t)
     * }
     */
    public static final long on_lobby_update$offset() {
        return on_lobby_update$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*on_lobby_update)(void *, int64_t)
     * }
     */
    public static MemorySegment on_lobby_update(MemorySegment struct) {
        return struct.get(on_lobby_update$LAYOUT, on_lobby_update$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*on_lobby_update)(void *, int64_t)
     * }
     */
    public static void on_lobby_update(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(on_lobby_update$LAYOUT, on_lobby_update$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*on_lobby_delete)(void *, int64_t, uint32_t)
     * }
     */
    public static class on_lobby_delete {

        on_lobby_delete() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, long _x1, int _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_LONG_LONG,
            discord_game_sdk_h.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr,MemorySegment _x0, long _x1, int _x2) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout on_lobby_delete$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("on_lobby_delete"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*on_lobby_delete)(void *, int64_t, uint32_t)
     * }
     */
    public static final AddressLayout on_lobby_delete$layout() {
        return on_lobby_delete$LAYOUT;
    }

    private static final long on_lobby_delete$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*on_lobby_delete)(void *, int64_t, uint32_t)
     * }
     */
    public static final long on_lobby_delete$offset() {
        return on_lobby_delete$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*on_lobby_delete)(void *, int64_t, uint32_t)
     * }
     */
    public static MemorySegment on_lobby_delete(MemorySegment struct) {
        return struct.get(on_lobby_delete$LAYOUT, on_lobby_delete$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*on_lobby_delete)(void *, int64_t, uint32_t)
     * }
     */
    public static void on_lobby_delete(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(on_lobby_delete$LAYOUT, on_lobby_delete$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*on_member_connect)(void *, int64_t, int64_t)
     * }
     */
    public static class on_member_connect {

        on_member_connect() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, long _x1, long _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_LONG_LONG,
            discord_game_sdk_h.C_LONG_LONG
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr,MemorySegment _x0, long _x1, long _x2) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout on_member_connect$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("on_member_connect"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*on_member_connect)(void *, int64_t, int64_t)
     * }
     */
    public static final AddressLayout on_member_connect$layout() {
        return on_member_connect$LAYOUT;
    }

    private static final long on_member_connect$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*on_member_connect)(void *, int64_t, int64_t)
     * }
     */
    public static final long on_member_connect$offset() {
        return on_member_connect$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*on_member_connect)(void *, int64_t, int64_t)
     * }
     */
    public static MemorySegment on_member_connect(MemorySegment struct) {
        return struct.get(on_member_connect$LAYOUT, on_member_connect$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*on_member_connect)(void *, int64_t, int64_t)
     * }
     */
    public static void on_member_connect(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(on_member_connect$LAYOUT, on_member_connect$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*on_member_update)(void *, int64_t, int64_t)
     * }
     */
    public static class on_member_update {

        on_member_update() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, long _x1, long _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_LONG_LONG,
            discord_game_sdk_h.C_LONG_LONG
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr,MemorySegment _x0, long _x1, long _x2) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout on_member_update$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("on_member_update"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*on_member_update)(void *, int64_t, int64_t)
     * }
     */
    public static final AddressLayout on_member_update$layout() {
        return on_member_update$LAYOUT;
    }

    private static final long on_member_update$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*on_member_update)(void *, int64_t, int64_t)
     * }
     */
    public static final long on_member_update$offset() {
        return on_member_update$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*on_member_update)(void *, int64_t, int64_t)
     * }
     */
    public static MemorySegment on_member_update(MemorySegment struct) {
        return struct.get(on_member_update$LAYOUT, on_member_update$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*on_member_update)(void *, int64_t, int64_t)
     * }
     */
    public static void on_member_update(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(on_member_update$LAYOUT, on_member_update$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*on_member_disconnect)(void *, int64_t, int64_t)
     * }
     */
    public static class on_member_disconnect {

        on_member_disconnect() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, long _x1, long _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_LONG_LONG,
            discord_game_sdk_h.C_LONG_LONG
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr,MemorySegment _x0, long _x1, long _x2) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout on_member_disconnect$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("on_member_disconnect"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*on_member_disconnect)(void *, int64_t, int64_t)
     * }
     */
    public static final AddressLayout on_member_disconnect$layout() {
        return on_member_disconnect$LAYOUT;
    }

    private static final long on_member_disconnect$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*on_member_disconnect)(void *, int64_t, int64_t)
     * }
     */
    public static final long on_member_disconnect$offset() {
        return on_member_disconnect$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*on_member_disconnect)(void *, int64_t, int64_t)
     * }
     */
    public static MemorySegment on_member_disconnect(MemorySegment struct) {
        return struct.get(on_member_disconnect$LAYOUT, on_member_disconnect$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*on_member_disconnect)(void *, int64_t, int64_t)
     * }
     */
    public static void on_member_disconnect(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(on_member_disconnect$LAYOUT, on_member_disconnect$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*on_lobby_message)(void *, int64_t, int64_t, uint8_t *, uint32_t)
     * }
     */
    public static class on_lobby_message {

        on_lobby_message() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, long _x1, long _x2, MemorySegment _x3, int _x4);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_LONG_LONG,
            discord_game_sdk_h.C_LONG_LONG,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr,MemorySegment _x0, long _x1, long _x2, MemorySegment _x3, int _x4) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout on_lobby_message$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("on_lobby_message"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*on_lobby_message)(void *, int64_t, int64_t, uint8_t *, uint32_t)
     * }
     */
    public static final AddressLayout on_lobby_message$layout() {
        return on_lobby_message$LAYOUT;
    }

    private static final long on_lobby_message$OFFSET = 40;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*on_lobby_message)(void *, int64_t, int64_t, uint8_t *, uint32_t)
     * }
     */
    public static final long on_lobby_message$offset() {
        return on_lobby_message$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*on_lobby_message)(void *, int64_t, int64_t, uint8_t *, uint32_t)
     * }
     */
    public static MemorySegment on_lobby_message(MemorySegment struct) {
        return struct.get(on_lobby_message$LAYOUT, on_lobby_message$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*on_lobby_message)(void *, int64_t, int64_t, uint8_t *, uint32_t)
     * }
     */
    public static void on_lobby_message(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(on_lobby_message$LAYOUT, on_lobby_message$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*on_speaking)(void *, int64_t, int64_t, bool)
     * }
     */
    public static class on_speaking {

        on_speaking() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, long _x1, long _x2, boolean _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_LONG_LONG,
            discord_game_sdk_h.C_LONG_LONG,
            discord_game_sdk_h.C_BOOL
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr,MemorySegment _x0, long _x1, long _x2, boolean _x3) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout on_speaking$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("on_speaking"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*on_speaking)(void *, int64_t, int64_t, bool)
     * }
     */
    public static final AddressLayout on_speaking$layout() {
        return on_speaking$LAYOUT;
    }

    private static final long on_speaking$OFFSET = 48;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*on_speaking)(void *, int64_t, int64_t, bool)
     * }
     */
    public static final long on_speaking$offset() {
        return on_speaking$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*on_speaking)(void *, int64_t, int64_t, bool)
     * }
     */
    public static MemorySegment on_speaking(MemorySegment struct) {
        return struct.get(on_speaking$LAYOUT, on_speaking$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*on_speaking)(void *, int64_t, int64_t, bool)
     * }
     */
    public static void on_speaking(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(on_speaking$LAYOUT, on_speaking$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*on_network_message)(void *, int64_t, int64_t, uint8_t, uint8_t *, uint32_t)
     * }
     */
    public static class on_network_message {

        on_network_message() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, long _x1, long _x2, byte _x3, MemorySegment _x4, int _x5);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_LONG_LONG,
            discord_game_sdk_h.C_LONG_LONG,
            discord_game_sdk_h.C_CHAR,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr,MemorySegment _x0, long _x1, long _x2, byte _x3, MemorySegment _x4, int _x5) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4, _x5);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout on_network_message$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("on_network_message"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*on_network_message)(void *, int64_t, int64_t, uint8_t, uint8_t *, uint32_t)
     * }
     */
    public static final AddressLayout on_network_message$layout() {
        return on_network_message$LAYOUT;
    }

    private static final long on_network_message$OFFSET = 56;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*on_network_message)(void *, int64_t, int64_t, uint8_t, uint8_t *, uint32_t)
     * }
     */
    public static final long on_network_message$offset() {
        return on_network_message$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*on_network_message)(void *, int64_t, int64_t, uint8_t, uint8_t *, uint32_t)
     * }
     */
    public static MemorySegment on_network_message(MemorySegment struct) {
        return struct.get(on_network_message$LAYOUT, on_network_message$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*on_network_message)(void *, int64_t, int64_t, uint8_t, uint8_t *, uint32_t)
     * }
     */
    public static void on_network_message(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(on_network_message$LAYOUT, on_network_message$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

