package discord.gamesdk;// Generated by jextract

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct IDiscordNetworkManager {
 *     void (*get_peer_id)(struct IDiscordNetworkManager *, DiscordNetworkPeerId *);
 *     enum EDiscordResult (*flush)(struct IDiscordNetworkManager *);
 *     enum EDiscordResult (*open_peer)(struct IDiscordNetworkManager *, DiscordNetworkPeerId, const char *);
 *     enum EDiscordResult (*update_peer)(struct IDiscordNetworkManager *, DiscordNetworkPeerId, const char *);
 *     enum EDiscordResult (*close_peer)(struct IDiscordNetworkManager *, DiscordNetworkPeerId);
 *     enum EDiscordResult (*open_channel)(struct IDiscordNetworkManager *, DiscordNetworkPeerId, DiscordNetworkChannelId, bool);
 *     enum EDiscordResult (*close_channel)(struct IDiscordNetworkManager *, DiscordNetworkPeerId, DiscordNetworkChannelId);
 *     enum EDiscordResult (*send_message)(struct IDiscordNetworkManager *, DiscordNetworkPeerId, DiscordNetworkChannelId, uint8_t *, uint32_t);
 * }
 * }
 */
public class IDiscordNetworkManager {

    IDiscordNetworkManager() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        discord_game_sdk_h.C_POINTER.withName("get_peer_id"),
        discord_game_sdk_h.C_POINTER.withName("flush"),
        discord_game_sdk_h.C_POINTER.withName("open_peer"),
        discord_game_sdk_h.C_POINTER.withName("update_peer"),
        discord_game_sdk_h.C_POINTER.withName("close_peer"),
        discord_game_sdk_h.C_POINTER.withName("open_channel"),
        discord_game_sdk_h.C_POINTER.withName("close_channel"),
        discord_game_sdk_h.C_POINTER.withName("send_message")
    ).withName("IDiscordNetworkManager");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * {@snippet lang=c :
     * void (*get_peer_id)(struct IDiscordNetworkManager *, DiscordNetworkPeerId *)
     * }
     */
    public static class get_peer_id {

        get_peer_id() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_peer_id$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_peer_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*get_peer_id)(struct IDiscordNetworkManager *, DiscordNetworkPeerId *)
     * }
     */
    public static final AddressLayout get_peer_id$layout() {
        return get_peer_id$LAYOUT;
    }

    private static final long get_peer_id$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*get_peer_id)(struct IDiscordNetworkManager *, DiscordNetworkPeerId *)
     * }
     */
    public static final long get_peer_id$offset() {
        return get_peer_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*get_peer_id)(struct IDiscordNetworkManager *, DiscordNetworkPeerId *)
     * }
     */
    public static MemorySegment get_peer_id(MemorySegment struct) {
        return struct.get(get_peer_id$LAYOUT, get_peer_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*get_peer_id)(struct IDiscordNetworkManager *, DiscordNetworkPeerId *)
     * }
     */
    public static void get_peer_id(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_peer_id$LAYOUT, get_peer_id$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * enum EDiscordResult (*flush)(struct IDiscordNetworkManager *)
     * }
     */
    public static class flush {

        flush() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_INT,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr,MemorySegment _x0) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout flush$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("flush"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*flush)(struct IDiscordNetworkManager *)
     * }
     */
    public static final AddressLayout flush$layout() {
        return flush$LAYOUT;
    }

    private static final long flush$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*flush)(struct IDiscordNetworkManager *)
     * }
     */
    public static final long flush$offset() {
        return flush$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*flush)(struct IDiscordNetworkManager *)
     * }
     */
    public static MemorySegment flush(MemorySegment struct) {
        return struct.get(flush$LAYOUT, flush$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*flush)(struct IDiscordNetworkManager *)
     * }
     */
    public static void flush(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(flush$LAYOUT, flush$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * enum EDiscordResult (*open_peer)(struct IDiscordNetworkManager *, DiscordNetworkPeerId, const char *)
     * }
     */
    public static class open_peer {

        open_peer() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, long _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_INT,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_LONG_LONG,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr,MemorySegment _x0, long _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout open_peer$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("open_peer"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*open_peer)(struct IDiscordNetworkManager *, DiscordNetworkPeerId, const char *)
     * }
     */
    public static final AddressLayout open_peer$layout() {
        return open_peer$LAYOUT;
    }

    private static final long open_peer$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*open_peer)(struct IDiscordNetworkManager *, DiscordNetworkPeerId, const char *)
     * }
     */
    public static final long open_peer$offset() {
        return open_peer$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*open_peer)(struct IDiscordNetworkManager *, DiscordNetworkPeerId, const char *)
     * }
     */
    public static MemorySegment open_peer(MemorySegment struct) {
        return struct.get(open_peer$LAYOUT, open_peer$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*open_peer)(struct IDiscordNetworkManager *, DiscordNetworkPeerId, const char *)
     * }
     */
    public static void open_peer(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(open_peer$LAYOUT, open_peer$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * enum EDiscordResult (*update_peer)(struct IDiscordNetworkManager *, DiscordNetworkPeerId, const char *)
     * }
     */
    public static class update_peer {

        update_peer() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, long _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_INT,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_LONG_LONG,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr,MemorySegment _x0, long _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout update_peer$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("update_peer"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*update_peer)(struct IDiscordNetworkManager *, DiscordNetworkPeerId, const char *)
     * }
     */
    public static final AddressLayout update_peer$layout() {
        return update_peer$LAYOUT;
    }

    private static final long update_peer$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*update_peer)(struct IDiscordNetworkManager *, DiscordNetworkPeerId, const char *)
     * }
     */
    public static final long update_peer$offset() {
        return update_peer$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*update_peer)(struct IDiscordNetworkManager *, DiscordNetworkPeerId, const char *)
     * }
     */
    public static MemorySegment update_peer(MemorySegment struct) {
        return struct.get(update_peer$LAYOUT, update_peer$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*update_peer)(struct IDiscordNetworkManager *, DiscordNetworkPeerId, const char *)
     * }
     */
    public static void update_peer(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(update_peer$LAYOUT, update_peer$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * enum EDiscordResult (*close_peer)(struct IDiscordNetworkManager *, DiscordNetworkPeerId)
     * }
     */
    public static class close_peer {

        close_peer() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, long _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_INT,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_LONG_LONG
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr,MemorySegment _x0, long _x1) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout close_peer$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("close_peer"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*close_peer)(struct IDiscordNetworkManager *, DiscordNetworkPeerId)
     * }
     */
    public static final AddressLayout close_peer$layout() {
        return close_peer$LAYOUT;
    }

    private static final long close_peer$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*close_peer)(struct IDiscordNetworkManager *, DiscordNetworkPeerId)
     * }
     */
    public static final long close_peer$offset() {
        return close_peer$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*close_peer)(struct IDiscordNetworkManager *, DiscordNetworkPeerId)
     * }
     */
    public static MemorySegment close_peer(MemorySegment struct) {
        return struct.get(close_peer$LAYOUT, close_peer$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*close_peer)(struct IDiscordNetworkManager *, DiscordNetworkPeerId)
     * }
     */
    public static void close_peer(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(close_peer$LAYOUT, close_peer$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * enum EDiscordResult (*open_channel)(struct IDiscordNetworkManager *, DiscordNetworkPeerId, DiscordNetworkChannelId, bool)
     * }
     */
    public static class open_channel {

        open_channel() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, long _x1, byte _x2, boolean _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_INT,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_LONG_LONG,
            discord_game_sdk_h.C_CHAR,
            discord_game_sdk_h.C_BOOL
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr,MemorySegment _x0, long _x1, byte _x2, boolean _x3) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout open_channel$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("open_channel"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*open_channel)(struct IDiscordNetworkManager *, DiscordNetworkPeerId, DiscordNetworkChannelId, bool)
     * }
     */
    public static final AddressLayout open_channel$layout() {
        return open_channel$LAYOUT;
    }

    private static final long open_channel$OFFSET = 40;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*open_channel)(struct IDiscordNetworkManager *, DiscordNetworkPeerId, DiscordNetworkChannelId, bool)
     * }
     */
    public static final long open_channel$offset() {
        return open_channel$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*open_channel)(struct IDiscordNetworkManager *, DiscordNetworkPeerId, DiscordNetworkChannelId, bool)
     * }
     */
    public static MemorySegment open_channel(MemorySegment struct) {
        return struct.get(open_channel$LAYOUT, open_channel$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*open_channel)(struct IDiscordNetworkManager *, DiscordNetworkPeerId, DiscordNetworkChannelId, bool)
     * }
     */
    public static void open_channel(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(open_channel$LAYOUT, open_channel$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * enum EDiscordResult (*close_channel)(struct IDiscordNetworkManager *, DiscordNetworkPeerId, DiscordNetworkChannelId)
     * }
     */
    public static class close_channel {

        close_channel() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, long _x1, byte _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_INT,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_LONG_LONG,
            discord_game_sdk_h.C_CHAR
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr,MemorySegment _x0, long _x1, byte _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout close_channel$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("close_channel"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*close_channel)(struct IDiscordNetworkManager *, DiscordNetworkPeerId, DiscordNetworkChannelId)
     * }
     */
    public static final AddressLayout close_channel$layout() {
        return close_channel$LAYOUT;
    }

    private static final long close_channel$OFFSET = 48;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*close_channel)(struct IDiscordNetworkManager *, DiscordNetworkPeerId, DiscordNetworkChannelId)
     * }
     */
    public static final long close_channel$offset() {
        return close_channel$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*close_channel)(struct IDiscordNetworkManager *, DiscordNetworkPeerId, DiscordNetworkChannelId)
     * }
     */
    public static MemorySegment close_channel(MemorySegment struct) {
        return struct.get(close_channel$LAYOUT, close_channel$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*close_channel)(struct IDiscordNetworkManager *, DiscordNetworkPeerId, DiscordNetworkChannelId)
     * }
     */
    public static void close_channel(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(close_channel$LAYOUT, close_channel$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * enum EDiscordResult (*send_message)(struct IDiscordNetworkManager *, DiscordNetworkPeerId, DiscordNetworkChannelId, uint8_t *, uint32_t)
     * }
     */
    public static class send_message {

        send_message() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, long _x1, byte _x2, MemorySegment _x3, int _x4);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_INT,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_LONG_LONG,
            discord_game_sdk_h.C_CHAR,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr,MemorySegment _x0, long _x1, byte _x2, MemorySegment _x3, int _x4) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout send_message$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("send_message"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*send_message)(struct IDiscordNetworkManager *, DiscordNetworkPeerId, DiscordNetworkChannelId, uint8_t *, uint32_t)
     * }
     */
    public static final AddressLayout send_message$layout() {
        return send_message$LAYOUT;
    }

    private static final long send_message$OFFSET = 56;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*send_message)(struct IDiscordNetworkManager *, DiscordNetworkPeerId, DiscordNetworkChannelId, uint8_t *, uint32_t)
     * }
     */
    public static final long send_message$offset() {
        return send_message$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*send_message)(struct IDiscordNetworkManager *, DiscordNetworkPeerId, DiscordNetworkChannelId, uint8_t *, uint32_t)
     * }
     */
    public static MemorySegment send_message(MemorySegment struct) {
        return struct.get(send_message$LAYOUT, send_message$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*send_message)(struct IDiscordNetworkManager *, DiscordNetworkPeerId, DiscordNetworkChannelId, uint8_t *, uint32_t)
     * }
     */
    public static void send_message(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(send_message$LAYOUT, send_message$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

