package discord.gamesdk;// Generated by jextract

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct IDiscordStoreManager {
 *     void (*fetch_skus)(struct IDiscordStoreManager *, void *, void (*)(void *, enum EDiscordResult));
 *     void (*count_skus)(struct IDiscordStoreManager *, int32_t *);
 *     enum EDiscordResult (*get_sku)(struct IDiscordStoreManager *, DiscordSnowflake, struct DiscordSku *);
 *     enum EDiscordResult (*get_sku_at)(struct IDiscordStoreManager *, int32_t, struct DiscordSku *);
 *     void (*fetch_entitlements)(struct IDiscordStoreManager *, void *, void (*)(void *, enum EDiscordResult));
 *     void (*count_entitlements)(struct IDiscordStoreManager *, int32_t *);
 *     enum EDiscordResult (*get_entitlement)(struct IDiscordStoreManager *, DiscordSnowflake, struct DiscordEntitlement *);
 *     enum EDiscordResult (*get_entitlement_at)(struct IDiscordStoreManager *, int32_t, struct DiscordEntitlement *);
 *     enum EDiscordResult (*has_sku_entitlement)(struct IDiscordStoreManager *, DiscordSnowflake, bool *);
 *     void (*start_purchase)(struct IDiscordStoreManager *, DiscordSnowflake, void *, void (*)(void *, enum EDiscordResult));
 * }
 * }
 */
public class IDiscordStoreManager {

    IDiscordStoreManager() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        discord_game_sdk_h.C_POINTER.withName("fetch_skus"),
        discord_game_sdk_h.C_POINTER.withName("count_skus"),
        discord_game_sdk_h.C_POINTER.withName("get_sku"),
        discord_game_sdk_h.C_POINTER.withName("get_sku_at"),
        discord_game_sdk_h.C_POINTER.withName("fetch_entitlements"),
        discord_game_sdk_h.C_POINTER.withName("count_entitlements"),
        discord_game_sdk_h.C_POINTER.withName("get_entitlement"),
        discord_game_sdk_h.C_POINTER.withName("get_entitlement_at"),
        discord_game_sdk_h.C_POINTER.withName("has_sku_entitlement"),
        discord_game_sdk_h.C_POINTER.withName("start_purchase")
    ).withName("IDiscordStoreManager");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * {@snippet lang=c :
     * void (*fetch_skus)(struct IDiscordStoreManager *, void *, void (*)(void *, enum EDiscordResult))
     * }
     */
    public static class fetch_skus {

        fetch_skus() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1, MemorySegment _x2) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout fetch_skus$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("fetch_skus"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*fetch_skus)(struct IDiscordStoreManager *, void *, void (*)(void *, enum EDiscordResult))
     * }
     */
    public static final AddressLayout fetch_skus$layout() {
        return fetch_skus$LAYOUT;
    }

    private static final long fetch_skus$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*fetch_skus)(struct IDiscordStoreManager *, void *, void (*)(void *, enum EDiscordResult))
     * }
     */
    public static final long fetch_skus$offset() {
        return fetch_skus$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*fetch_skus)(struct IDiscordStoreManager *, void *, void (*)(void *, enum EDiscordResult))
     * }
     */
    public static MemorySegment fetch_skus(MemorySegment struct) {
        return struct.get(fetch_skus$LAYOUT, fetch_skus$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*fetch_skus)(struct IDiscordStoreManager *, void *, void (*)(void *, enum EDiscordResult))
     * }
     */
    public static void fetch_skus(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(fetch_skus$LAYOUT, fetch_skus$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*count_skus)(struct IDiscordStoreManager *, int32_t *)
     * }
     */
    public static class count_skus {

        count_skus() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout count_skus$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("count_skus"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*count_skus)(struct IDiscordStoreManager *, int32_t *)
     * }
     */
    public static final AddressLayout count_skus$layout() {
        return count_skus$LAYOUT;
    }

    private static final long count_skus$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*count_skus)(struct IDiscordStoreManager *, int32_t *)
     * }
     */
    public static final long count_skus$offset() {
        return count_skus$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*count_skus)(struct IDiscordStoreManager *, int32_t *)
     * }
     */
    public static MemorySegment count_skus(MemorySegment struct) {
        return struct.get(count_skus$LAYOUT, count_skus$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*count_skus)(struct IDiscordStoreManager *, int32_t *)
     * }
     */
    public static void count_skus(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(count_skus$LAYOUT, count_skus$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * enum EDiscordResult (*get_sku)(struct IDiscordStoreManager *, DiscordSnowflake, struct DiscordSku *)
     * }
     */
    public static class get_sku {

        get_sku() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, long _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_INT,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_LONG_LONG,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr,MemorySegment _x0, long _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_sku$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_sku"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*get_sku)(struct IDiscordStoreManager *, DiscordSnowflake, struct DiscordSku *)
     * }
     */
    public static final AddressLayout get_sku$layout() {
        return get_sku$LAYOUT;
    }

    private static final long get_sku$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*get_sku)(struct IDiscordStoreManager *, DiscordSnowflake, struct DiscordSku *)
     * }
     */
    public static final long get_sku$offset() {
        return get_sku$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*get_sku)(struct IDiscordStoreManager *, DiscordSnowflake, struct DiscordSku *)
     * }
     */
    public static MemorySegment get_sku(MemorySegment struct) {
        return struct.get(get_sku$LAYOUT, get_sku$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*get_sku)(struct IDiscordStoreManager *, DiscordSnowflake, struct DiscordSku *)
     * }
     */
    public static void get_sku(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_sku$LAYOUT, get_sku$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * enum EDiscordResult (*get_sku_at)(struct IDiscordStoreManager *, int32_t, struct DiscordSku *)
     * }
     */
    public static class get_sku_at {

        get_sku_at() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_INT,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_INT,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr,MemorySegment _x0, int _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_sku_at$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_sku_at"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*get_sku_at)(struct IDiscordStoreManager *, int32_t, struct DiscordSku *)
     * }
     */
    public static final AddressLayout get_sku_at$layout() {
        return get_sku_at$LAYOUT;
    }

    private static final long get_sku_at$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*get_sku_at)(struct IDiscordStoreManager *, int32_t, struct DiscordSku *)
     * }
     */
    public static final long get_sku_at$offset() {
        return get_sku_at$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*get_sku_at)(struct IDiscordStoreManager *, int32_t, struct DiscordSku *)
     * }
     */
    public static MemorySegment get_sku_at(MemorySegment struct) {
        return struct.get(get_sku_at$LAYOUT, get_sku_at$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*get_sku_at)(struct IDiscordStoreManager *, int32_t, struct DiscordSku *)
     * }
     */
    public static void get_sku_at(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_sku_at$LAYOUT, get_sku_at$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*fetch_entitlements)(struct IDiscordStoreManager *, void *, void (*)(void *, enum EDiscordResult))
     * }
     */
    public static class fetch_entitlements {

        fetch_entitlements() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1, MemorySegment _x2) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout fetch_entitlements$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("fetch_entitlements"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*fetch_entitlements)(struct IDiscordStoreManager *, void *, void (*)(void *, enum EDiscordResult))
     * }
     */
    public static final AddressLayout fetch_entitlements$layout() {
        return fetch_entitlements$LAYOUT;
    }

    private static final long fetch_entitlements$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*fetch_entitlements)(struct IDiscordStoreManager *, void *, void (*)(void *, enum EDiscordResult))
     * }
     */
    public static final long fetch_entitlements$offset() {
        return fetch_entitlements$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*fetch_entitlements)(struct IDiscordStoreManager *, void *, void (*)(void *, enum EDiscordResult))
     * }
     */
    public static MemorySegment fetch_entitlements(MemorySegment struct) {
        return struct.get(fetch_entitlements$LAYOUT, fetch_entitlements$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*fetch_entitlements)(struct IDiscordStoreManager *, void *, void (*)(void *, enum EDiscordResult))
     * }
     */
    public static void fetch_entitlements(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(fetch_entitlements$LAYOUT, fetch_entitlements$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*count_entitlements)(struct IDiscordStoreManager *, int32_t *)
     * }
     */
    public static class count_entitlements {

        count_entitlements() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout count_entitlements$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("count_entitlements"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*count_entitlements)(struct IDiscordStoreManager *, int32_t *)
     * }
     */
    public static final AddressLayout count_entitlements$layout() {
        return count_entitlements$LAYOUT;
    }

    private static final long count_entitlements$OFFSET = 40;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*count_entitlements)(struct IDiscordStoreManager *, int32_t *)
     * }
     */
    public static final long count_entitlements$offset() {
        return count_entitlements$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*count_entitlements)(struct IDiscordStoreManager *, int32_t *)
     * }
     */
    public static MemorySegment count_entitlements(MemorySegment struct) {
        return struct.get(count_entitlements$LAYOUT, count_entitlements$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*count_entitlements)(struct IDiscordStoreManager *, int32_t *)
     * }
     */
    public static void count_entitlements(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(count_entitlements$LAYOUT, count_entitlements$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * enum EDiscordResult (*get_entitlement)(struct IDiscordStoreManager *, DiscordSnowflake, struct DiscordEntitlement *)
     * }
     */
    public static class get_entitlement {

        get_entitlement() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, long _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_INT,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_LONG_LONG,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr,MemorySegment _x0, long _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_entitlement$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_entitlement"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*get_entitlement)(struct IDiscordStoreManager *, DiscordSnowflake, struct DiscordEntitlement *)
     * }
     */
    public static final AddressLayout get_entitlement$layout() {
        return get_entitlement$LAYOUT;
    }

    private static final long get_entitlement$OFFSET = 48;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*get_entitlement)(struct IDiscordStoreManager *, DiscordSnowflake, struct DiscordEntitlement *)
     * }
     */
    public static final long get_entitlement$offset() {
        return get_entitlement$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*get_entitlement)(struct IDiscordStoreManager *, DiscordSnowflake, struct DiscordEntitlement *)
     * }
     */
    public static MemorySegment get_entitlement(MemorySegment struct) {
        return struct.get(get_entitlement$LAYOUT, get_entitlement$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*get_entitlement)(struct IDiscordStoreManager *, DiscordSnowflake, struct DiscordEntitlement *)
     * }
     */
    public static void get_entitlement(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_entitlement$LAYOUT, get_entitlement$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * enum EDiscordResult (*get_entitlement_at)(struct IDiscordStoreManager *, int32_t, struct DiscordEntitlement *)
     * }
     */
    public static class get_entitlement_at {

        get_entitlement_at() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_INT,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_INT,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr,MemorySegment _x0, int _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_entitlement_at$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_entitlement_at"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*get_entitlement_at)(struct IDiscordStoreManager *, int32_t, struct DiscordEntitlement *)
     * }
     */
    public static final AddressLayout get_entitlement_at$layout() {
        return get_entitlement_at$LAYOUT;
    }

    private static final long get_entitlement_at$OFFSET = 56;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*get_entitlement_at)(struct IDiscordStoreManager *, int32_t, struct DiscordEntitlement *)
     * }
     */
    public static final long get_entitlement_at$offset() {
        return get_entitlement_at$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*get_entitlement_at)(struct IDiscordStoreManager *, int32_t, struct DiscordEntitlement *)
     * }
     */
    public static MemorySegment get_entitlement_at(MemorySegment struct) {
        return struct.get(get_entitlement_at$LAYOUT, get_entitlement_at$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*get_entitlement_at)(struct IDiscordStoreManager *, int32_t, struct DiscordEntitlement *)
     * }
     */
    public static void get_entitlement_at(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_entitlement_at$LAYOUT, get_entitlement_at$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * enum EDiscordResult (*has_sku_entitlement)(struct IDiscordStoreManager *, DiscordSnowflake, bool *)
     * }
     */
    public static class has_sku_entitlement {

        has_sku_entitlement() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, long _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_INT,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_LONG_LONG,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr,MemorySegment _x0, long _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout has_sku_entitlement$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("has_sku_entitlement"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*has_sku_entitlement)(struct IDiscordStoreManager *, DiscordSnowflake, bool *)
     * }
     */
    public static final AddressLayout has_sku_entitlement$layout() {
        return has_sku_entitlement$LAYOUT;
    }

    private static final long has_sku_entitlement$OFFSET = 64;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*has_sku_entitlement)(struct IDiscordStoreManager *, DiscordSnowflake, bool *)
     * }
     */
    public static final long has_sku_entitlement$offset() {
        return has_sku_entitlement$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*has_sku_entitlement)(struct IDiscordStoreManager *, DiscordSnowflake, bool *)
     * }
     */
    public static MemorySegment has_sku_entitlement(MemorySegment struct) {
        return struct.get(has_sku_entitlement$LAYOUT, has_sku_entitlement$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*has_sku_entitlement)(struct IDiscordStoreManager *, DiscordSnowflake, bool *)
     * }
     */
    public static void has_sku_entitlement(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(has_sku_entitlement$LAYOUT, has_sku_entitlement$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*start_purchase)(struct IDiscordStoreManager *, DiscordSnowflake, void *, void (*)(void *, enum EDiscordResult))
     * }
     */
    public static class start_purchase {

        start_purchase() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, long _x1, MemorySegment _x2, MemorySegment _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_LONG_LONG,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr,MemorySegment _x0, long _x1, MemorySegment _x2, MemorySegment _x3) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout start_purchase$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("start_purchase"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*start_purchase)(struct IDiscordStoreManager *, DiscordSnowflake, void *, void (*)(void *, enum EDiscordResult))
     * }
     */
    public static final AddressLayout start_purchase$layout() {
        return start_purchase$LAYOUT;
    }

    private static final long start_purchase$OFFSET = 72;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*start_purchase)(struct IDiscordStoreManager *, DiscordSnowflake, void *, void (*)(void *, enum EDiscordResult))
     * }
     */
    public static final long start_purchase$offset() {
        return start_purchase$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*start_purchase)(struct IDiscordStoreManager *, DiscordSnowflake, void *, void (*)(void *, enum EDiscordResult))
     * }
     */
    public static MemorySegment start_purchase(MemorySegment struct) {
        return struct.get(start_purchase$LAYOUT, start_purchase$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*start_purchase)(struct IDiscordStoreManager *, DiscordSnowflake, void *, void (*)(void *, enum EDiscordResult))
     * }
     */
    public static void start_purchase(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(start_purchase$LAYOUT, start_purchase$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

