package discord.gamesdk;// Generated by jextract

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct IDiscordCore {
 *     void (*destroy)(struct IDiscordCore *);
 *     enum EDiscordResult (*run_callbacks)(struct IDiscordCore *);
 *     void (*set_log_hook)(struct IDiscordCore *, enum EDiscordLogLevel, void *, void (*)(void *, enum EDiscordLogLevel, const char *));
 *     struct IDiscordApplicationManager *(*get_application_manager)(struct IDiscordCore *);
 *     struct IDiscordUserManager *(*get_user_manager)(struct IDiscordCore *);
 *     struct IDiscordImageManager *(*get_image_manager)(struct IDiscordCore *);
 *     struct IDiscordActivityManager *(*get_activity_manager)(struct IDiscordCore *);
 *     struct IDiscordRelationshipManager *(*get_relationship_manager)(struct IDiscordCore *);
 *     struct IDiscordLobbyManager *(*get_lobby_manager)(struct IDiscordCore *);
 *     struct IDiscordNetworkManager *(*get_network_manager)(struct IDiscordCore *);
 *     struct IDiscordOverlayManager *(*get_overlay_manager)(struct IDiscordCore *);
 *     struct IDiscordStorageManager *(*get_storage_manager)(struct IDiscordCore *);
 *     struct IDiscordStoreManager *(*get_store_manager)(struct IDiscordCore *);
 *     struct IDiscordVoiceManager *(*get_voice_manager)(struct IDiscordCore *);
 *     struct IDiscordAchievementManager *(*get_achievement_manager)(struct IDiscordCore *);
 * }
 * }
 */
public class IDiscordCore {

    IDiscordCore() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        discord_game_sdk_h.C_POINTER.withName("destroy"),
        discord_game_sdk_h.C_POINTER.withName("run_callbacks"),
        discord_game_sdk_h.C_POINTER.withName("set_log_hook"),
        discord_game_sdk_h.C_POINTER.withName("get_application_manager"),
        discord_game_sdk_h.C_POINTER.withName("get_user_manager"),
        discord_game_sdk_h.C_POINTER.withName("get_image_manager"),
        discord_game_sdk_h.C_POINTER.withName("get_activity_manager"),
        discord_game_sdk_h.C_POINTER.withName("get_relationship_manager"),
        discord_game_sdk_h.C_POINTER.withName("get_lobby_manager"),
        discord_game_sdk_h.C_POINTER.withName("get_network_manager"),
        discord_game_sdk_h.C_POINTER.withName("get_overlay_manager"),
        discord_game_sdk_h.C_POINTER.withName("get_storage_manager"),
        discord_game_sdk_h.C_POINTER.withName("get_store_manager"),
        discord_game_sdk_h.C_POINTER.withName("get_voice_manager"),
        discord_game_sdk_h.C_POINTER.withName("get_achievement_manager")
    ).withName("IDiscordCore");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * {@snippet lang=c :
     * void (*destroy)(struct IDiscordCore *)
     * }
     */
    public static class destroy {

        destroy() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr,MemorySegment _x0) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout destroy$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("destroy"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*destroy)(struct IDiscordCore *)
     * }
     */
    public static final AddressLayout destroy$layout() {
        return destroy$LAYOUT;
    }

    private static final long destroy$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*destroy)(struct IDiscordCore *)
     * }
     */
    public static final long destroy$offset() {
        return destroy$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*destroy)(struct IDiscordCore *)
     * }
     */
    public static MemorySegment destroy(MemorySegment struct) {
        return struct.get(destroy$LAYOUT, destroy$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*destroy)(struct IDiscordCore *)
     * }
     */
    public static void destroy(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(destroy$LAYOUT, destroy$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * enum EDiscordResult (*run_callbacks)(struct IDiscordCore *)
     * }
     */
    public static class run_callbacks {

        run_callbacks() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_INT,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr,MemorySegment _x0) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout run_callbacks$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("run_callbacks"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*run_callbacks)(struct IDiscordCore *)
     * }
     */
    public static final AddressLayout run_callbacks$layout() {
        return run_callbacks$LAYOUT;
    }

    private static final long run_callbacks$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*run_callbacks)(struct IDiscordCore *)
     * }
     */
    public static final long run_callbacks$offset() {
        return run_callbacks$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*run_callbacks)(struct IDiscordCore *)
     * }
     */
    public static MemorySegment run_callbacks(MemorySegment struct) {
        return struct.get(run_callbacks$LAYOUT, run_callbacks$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*run_callbacks)(struct IDiscordCore *)
     * }
     */
    public static void run_callbacks(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(run_callbacks$LAYOUT, run_callbacks$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*set_log_hook)(struct IDiscordCore *, enum EDiscordLogLevel, void *, void (*)(void *, enum EDiscordLogLevel, const char *))
     * }
     */
    public static class set_log_hook {

        set_log_hook() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, int _x1, MemorySegment _x2, MemorySegment _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_INT,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr,MemorySegment _x0, int _x1, MemorySegment _x2, MemorySegment _x3) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout set_log_hook$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("set_log_hook"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*set_log_hook)(struct IDiscordCore *, enum EDiscordLogLevel, void *, void (*)(void *, enum EDiscordLogLevel, const char *))
     * }
     */
    public static final AddressLayout set_log_hook$layout() {
        return set_log_hook$LAYOUT;
    }

    private static final long set_log_hook$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*set_log_hook)(struct IDiscordCore *, enum EDiscordLogLevel, void *, void (*)(void *, enum EDiscordLogLevel, const char *))
     * }
     */
    public static final long set_log_hook$offset() {
        return set_log_hook$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*set_log_hook)(struct IDiscordCore *, enum EDiscordLogLevel, void *, void (*)(void *, enum EDiscordLogLevel, const char *))
     * }
     */
    public static MemorySegment set_log_hook(MemorySegment struct) {
        return struct.get(set_log_hook$LAYOUT, set_log_hook$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*set_log_hook)(struct IDiscordCore *, enum EDiscordLogLevel, void *, void (*)(void *, enum EDiscordLogLevel, const char *))
     * }
     */
    public static void set_log_hook(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(set_log_hook$LAYOUT, set_log_hook$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * struct IDiscordApplicationManager *(*get_application_manager)(struct IDiscordCore *)
     * }
     */
    public static class get_application_manager {

        get_application_manager() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr,MemorySegment _x0) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_application_manager$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_application_manager"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct IDiscordApplicationManager *(*get_application_manager)(struct IDiscordCore *)
     * }
     */
    public static final AddressLayout get_application_manager$layout() {
        return get_application_manager$LAYOUT;
    }

    private static final long get_application_manager$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct IDiscordApplicationManager *(*get_application_manager)(struct IDiscordCore *)
     * }
     */
    public static final long get_application_manager$offset() {
        return get_application_manager$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct IDiscordApplicationManager *(*get_application_manager)(struct IDiscordCore *)
     * }
     */
    public static MemorySegment get_application_manager(MemorySegment struct) {
        return struct.get(get_application_manager$LAYOUT, get_application_manager$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct IDiscordApplicationManager *(*get_application_manager)(struct IDiscordCore *)
     * }
     */
    public static void get_application_manager(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_application_manager$LAYOUT, get_application_manager$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * struct IDiscordUserManager *(*get_user_manager)(struct IDiscordCore *)
     * }
     */
    public static class get_user_manager {

        get_user_manager() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr,MemorySegment _x0) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_user_manager$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_user_manager"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct IDiscordUserManager *(*get_user_manager)(struct IDiscordCore *)
     * }
     */
    public static final AddressLayout get_user_manager$layout() {
        return get_user_manager$LAYOUT;
    }

    private static final long get_user_manager$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct IDiscordUserManager *(*get_user_manager)(struct IDiscordCore *)
     * }
     */
    public static final long get_user_manager$offset() {
        return get_user_manager$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct IDiscordUserManager *(*get_user_manager)(struct IDiscordCore *)
     * }
     */
    public static MemorySegment get_user_manager(MemorySegment struct) {
        return struct.get(get_user_manager$LAYOUT, get_user_manager$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct IDiscordUserManager *(*get_user_manager)(struct IDiscordCore *)
     * }
     */
    public static void get_user_manager(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_user_manager$LAYOUT, get_user_manager$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * struct IDiscordImageManager *(*get_image_manager)(struct IDiscordCore *)
     * }
     */
    public static class get_image_manager {

        get_image_manager() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr,MemorySegment _x0) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_image_manager$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_image_manager"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct IDiscordImageManager *(*get_image_manager)(struct IDiscordCore *)
     * }
     */
    public static final AddressLayout get_image_manager$layout() {
        return get_image_manager$LAYOUT;
    }

    private static final long get_image_manager$OFFSET = 40;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct IDiscordImageManager *(*get_image_manager)(struct IDiscordCore *)
     * }
     */
    public static final long get_image_manager$offset() {
        return get_image_manager$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct IDiscordImageManager *(*get_image_manager)(struct IDiscordCore *)
     * }
     */
    public static MemorySegment get_image_manager(MemorySegment struct) {
        return struct.get(get_image_manager$LAYOUT, get_image_manager$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct IDiscordImageManager *(*get_image_manager)(struct IDiscordCore *)
     * }
     */
    public static void get_image_manager(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_image_manager$LAYOUT, get_image_manager$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * struct IDiscordActivityManager *(*get_activity_manager)(struct IDiscordCore *)
     * }
     */
    public static class get_activity_manager {

        get_activity_manager() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr,MemorySegment _x0) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_activity_manager$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_activity_manager"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct IDiscordActivityManager *(*get_activity_manager)(struct IDiscordCore *)
     * }
     */
    public static final AddressLayout get_activity_manager$layout() {
        return get_activity_manager$LAYOUT;
    }

    private static final long get_activity_manager$OFFSET = 48;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct IDiscordActivityManager *(*get_activity_manager)(struct IDiscordCore *)
     * }
     */
    public static final long get_activity_manager$offset() {
        return get_activity_manager$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct IDiscordActivityManager *(*get_activity_manager)(struct IDiscordCore *)
     * }
     */
    public static MemorySegment get_activity_manager(MemorySegment struct) {
        return struct.get(get_activity_manager$LAYOUT, get_activity_manager$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct IDiscordActivityManager *(*get_activity_manager)(struct IDiscordCore *)
     * }
     */
    public static void get_activity_manager(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_activity_manager$LAYOUT, get_activity_manager$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * struct IDiscordRelationshipManager *(*get_relationship_manager)(struct IDiscordCore *)
     * }
     */
    public static class get_relationship_manager {

        get_relationship_manager() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr,MemorySegment _x0) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_relationship_manager$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_relationship_manager"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct IDiscordRelationshipManager *(*get_relationship_manager)(struct IDiscordCore *)
     * }
     */
    public static final AddressLayout get_relationship_manager$layout() {
        return get_relationship_manager$LAYOUT;
    }

    private static final long get_relationship_manager$OFFSET = 56;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct IDiscordRelationshipManager *(*get_relationship_manager)(struct IDiscordCore *)
     * }
     */
    public static final long get_relationship_manager$offset() {
        return get_relationship_manager$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct IDiscordRelationshipManager *(*get_relationship_manager)(struct IDiscordCore *)
     * }
     */
    public static MemorySegment get_relationship_manager(MemorySegment struct) {
        return struct.get(get_relationship_manager$LAYOUT, get_relationship_manager$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct IDiscordRelationshipManager *(*get_relationship_manager)(struct IDiscordCore *)
     * }
     */
    public static void get_relationship_manager(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_relationship_manager$LAYOUT, get_relationship_manager$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * struct IDiscordLobbyManager *(*get_lobby_manager)(struct IDiscordCore *)
     * }
     */
    public static class get_lobby_manager {

        get_lobby_manager() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr,MemorySegment _x0) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_lobby_manager$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_lobby_manager"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct IDiscordLobbyManager *(*get_lobby_manager)(struct IDiscordCore *)
     * }
     */
    public static final AddressLayout get_lobby_manager$layout() {
        return get_lobby_manager$LAYOUT;
    }

    private static final long get_lobby_manager$OFFSET = 64;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct IDiscordLobbyManager *(*get_lobby_manager)(struct IDiscordCore *)
     * }
     */
    public static final long get_lobby_manager$offset() {
        return get_lobby_manager$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct IDiscordLobbyManager *(*get_lobby_manager)(struct IDiscordCore *)
     * }
     */
    public static MemorySegment get_lobby_manager(MemorySegment struct) {
        return struct.get(get_lobby_manager$LAYOUT, get_lobby_manager$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct IDiscordLobbyManager *(*get_lobby_manager)(struct IDiscordCore *)
     * }
     */
    public static void get_lobby_manager(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_lobby_manager$LAYOUT, get_lobby_manager$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * struct IDiscordNetworkManager *(*get_network_manager)(struct IDiscordCore *)
     * }
     */
    public static class get_network_manager {

        get_network_manager() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr,MemorySegment _x0) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_network_manager$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_network_manager"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct IDiscordNetworkManager *(*get_network_manager)(struct IDiscordCore *)
     * }
     */
    public static final AddressLayout get_network_manager$layout() {
        return get_network_manager$LAYOUT;
    }

    private static final long get_network_manager$OFFSET = 72;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct IDiscordNetworkManager *(*get_network_manager)(struct IDiscordCore *)
     * }
     */
    public static final long get_network_manager$offset() {
        return get_network_manager$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct IDiscordNetworkManager *(*get_network_manager)(struct IDiscordCore *)
     * }
     */
    public static MemorySegment get_network_manager(MemorySegment struct) {
        return struct.get(get_network_manager$LAYOUT, get_network_manager$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct IDiscordNetworkManager *(*get_network_manager)(struct IDiscordCore *)
     * }
     */
    public static void get_network_manager(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_network_manager$LAYOUT, get_network_manager$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * struct IDiscordOverlayManager *(*get_overlay_manager)(struct IDiscordCore *)
     * }
     */
    public static class get_overlay_manager {

        get_overlay_manager() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr,MemorySegment _x0) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_overlay_manager$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_overlay_manager"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct IDiscordOverlayManager *(*get_overlay_manager)(struct IDiscordCore *)
     * }
     */
    public static final AddressLayout get_overlay_manager$layout() {
        return get_overlay_manager$LAYOUT;
    }

    private static final long get_overlay_manager$OFFSET = 80;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct IDiscordOverlayManager *(*get_overlay_manager)(struct IDiscordCore *)
     * }
     */
    public static final long get_overlay_manager$offset() {
        return get_overlay_manager$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct IDiscordOverlayManager *(*get_overlay_manager)(struct IDiscordCore *)
     * }
     */
    public static MemorySegment get_overlay_manager(MemorySegment struct) {
        return struct.get(get_overlay_manager$LAYOUT, get_overlay_manager$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct IDiscordOverlayManager *(*get_overlay_manager)(struct IDiscordCore *)
     * }
     */
    public static void get_overlay_manager(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_overlay_manager$LAYOUT, get_overlay_manager$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * struct IDiscordStorageManager *(*get_storage_manager)(struct IDiscordCore *)
     * }
     */
    public static class get_storage_manager {

        get_storage_manager() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr,MemorySegment _x0) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_storage_manager$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_storage_manager"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct IDiscordStorageManager *(*get_storage_manager)(struct IDiscordCore *)
     * }
     */
    public static final AddressLayout get_storage_manager$layout() {
        return get_storage_manager$LAYOUT;
    }

    private static final long get_storage_manager$OFFSET = 88;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct IDiscordStorageManager *(*get_storage_manager)(struct IDiscordCore *)
     * }
     */
    public static final long get_storage_manager$offset() {
        return get_storage_manager$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct IDiscordStorageManager *(*get_storage_manager)(struct IDiscordCore *)
     * }
     */
    public static MemorySegment get_storage_manager(MemorySegment struct) {
        return struct.get(get_storage_manager$LAYOUT, get_storage_manager$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct IDiscordStorageManager *(*get_storage_manager)(struct IDiscordCore *)
     * }
     */
    public static void get_storage_manager(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_storage_manager$LAYOUT, get_storage_manager$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * struct IDiscordStoreManager *(*get_store_manager)(struct IDiscordCore *)
     * }
     */
    public static class get_store_manager {

        get_store_manager() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr,MemorySegment _x0) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_store_manager$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_store_manager"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct IDiscordStoreManager *(*get_store_manager)(struct IDiscordCore *)
     * }
     */
    public static final AddressLayout get_store_manager$layout() {
        return get_store_manager$LAYOUT;
    }

    private static final long get_store_manager$OFFSET = 96;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct IDiscordStoreManager *(*get_store_manager)(struct IDiscordCore *)
     * }
     */
    public static final long get_store_manager$offset() {
        return get_store_manager$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct IDiscordStoreManager *(*get_store_manager)(struct IDiscordCore *)
     * }
     */
    public static MemorySegment get_store_manager(MemorySegment struct) {
        return struct.get(get_store_manager$LAYOUT, get_store_manager$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct IDiscordStoreManager *(*get_store_manager)(struct IDiscordCore *)
     * }
     */
    public static void get_store_manager(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_store_manager$LAYOUT, get_store_manager$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * struct IDiscordVoiceManager *(*get_voice_manager)(struct IDiscordCore *)
     * }
     */
    public static class get_voice_manager {

        get_voice_manager() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr,MemorySegment _x0) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_voice_manager$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_voice_manager"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct IDiscordVoiceManager *(*get_voice_manager)(struct IDiscordCore *)
     * }
     */
    public static final AddressLayout get_voice_manager$layout() {
        return get_voice_manager$LAYOUT;
    }

    private static final long get_voice_manager$OFFSET = 104;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct IDiscordVoiceManager *(*get_voice_manager)(struct IDiscordCore *)
     * }
     */
    public static final long get_voice_manager$offset() {
        return get_voice_manager$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct IDiscordVoiceManager *(*get_voice_manager)(struct IDiscordCore *)
     * }
     */
    public static MemorySegment get_voice_manager(MemorySegment struct) {
        return struct.get(get_voice_manager$LAYOUT, get_voice_manager$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct IDiscordVoiceManager *(*get_voice_manager)(struct IDiscordCore *)
     * }
     */
    public static void get_voice_manager(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_voice_manager$LAYOUT, get_voice_manager$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * struct IDiscordAchievementManager *(*get_achievement_manager)(struct IDiscordCore *)
     * }
     */
    public static class get_achievement_manager {

        get_achievement_manager() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr,MemorySegment _x0) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_achievement_manager$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_achievement_manager"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct IDiscordAchievementManager *(*get_achievement_manager)(struct IDiscordCore *)
     * }
     */
    public static final AddressLayout get_achievement_manager$layout() {
        return get_achievement_manager$LAYOUT;
    }

    private static final long get_achievement_manager$OFFSET = 112;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct IDiscordAchievementManager *(*get_achievement_manager)(struct IDiscordCore *)
     * }
     */
    public static final long get_achievement_manager$offset() {
        return get_achievement_manager$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct IDiscordAchievementManager *(*get_achievement_manager)(struct IDiscordCore *)
     * }
     */
    public static MemorySegment get_achievement_manager(MemorySegment struct) {
        return struct.get(get_achievement_manager$LAYOUT, get_achievement_manager$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct IDiscordAchievementManager *(*get_achievement_manager)(struct IDiscordCore *)
     * }
     */
    public static void get_achievement_manager(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_achievement_manager$LAYOUT, get_achievement_manager$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

