package discord.gamesdk;// Generated by jextract

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct IDiscordAchievementManager {
 *     void (*set_user_achievement)(struct IDiscordAchievementManager *, DiscordSnowflake, uint8_t, void *, void (*)(void *, enum EDiscordResult));
 *     void (*fetch_user_achievements)(struct IDiscordAchievementManager *, void *, void (*)(void *, enum EDiscordResult));
 *     void (*count_user_achievements)(struct IDiscordAchievementManager *, int32_t *);
 *     enum EDiscordResult (*get_user_achievement)(struct IDiscordAchievementManager *, DiscordSnowflake, struct DiscordUserAchievement *);
 *     enum EDiscordResult (*get_user_achievement_at)(struct IDiscordAchievementManager *, int32_t, struct DiscordUserAchievement *);
 * }
 * }
 */
public class IDiscordAchievementManager {

    IDiscordAchievementManager() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        discord_game_sdk_h.C_POINTER.withName("set_user_achievement"),
        discord_game_sdk_h.C_POINTER.withName("fetch_user_achievements"),
        discord_game_sdk_h.C_POINTER.withName("count_user_achievements"),
        discord_game_sdk_h.C_POINTER.withName("get_user_achievement"),
        discord_game_sdk_h.C_POINTER.withName("get_user_achievement_at")
    ).withName("IDiscordAchievementManager");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * {@snippet lang=c :
     * void (*set_user_achievement)(struct IDiscordAchievementManager *, DiscordSnowflake, uint8_t, void *, void (*)(void *, enum EDiscordResult))
     * }
     */
    public static class set_user_achievement {

        set_user_achievement() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, long _x1, byte _x2, MemorySegment _x3, MemorySegment _x4);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_LONG_LONG,
            discord_game_sdk_h.C_CHAR,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr,MemorySegment _x0, long _x1, byte _x2, MemorySegment _x3, MemorySegment _x4) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout set_user_achievement$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("set_user_achievement"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*set_user_achievement)(struct IDiscordAchievementManager *, DiscordSnowflake, uint8_t, void *, void (*)(void *, enum EDiscordResult))
     * }
     */
    public static final AddressLayout set_user_achievement$layout() {
        return set_user_achievement$LAYOUT;
    }

    private static final long set_user_achievement$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*set_user_achievement)(struct IDiscordAchievementManager *, DiscordSnowflake, uint8_t, void *, void (*)(void *, enum EDiscordResult))
     * }
     */
    public static final long set_user_achievement$offset() {
        return set_user_achievement$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*set_user_achievement)(struct IDiscordAchievementManager *, DiscordSnowflake, uint8_t, void *, void (*)(void *, enum EDiscordResult))
     * }
     */
    public static MemorySegment set_user_achievement(MemorySegment struct) {
        return struct.get(set_user_achievement$LAYOUT, set_user_achievement$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*set_user_achievement)(struct IDiscordAchievementManager *, DiscordSnowflake, uint8_t, void *, void (*)(void *, enum EDiscordResult))
     * }
     */
    public static void set_user_achievement(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(set_user_achievement$LAYOUT, set_user_achievement$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*fetch_user_achievements)(struct IDiscordAchievementManager *, void *, void (*)(void *, enum EDiscordResult))
     * }
     */
    public static class fetch_user_achievements {

        fetch_user_achievements() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1, MemorySegment _x2) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout fetch_user_achievements$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("fetch_user_achievements"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*fetch_user_achievements)(struct IDiscordAchievementManager *, void *, void (*)(void *, enum EDiscordResult))
     * }
     */
    public static final AddressLayout fetch_user_achievements$layout() {
        return fetch_user_achievements$LAYOUT;
    }

    private static final long fetch_user_achievements$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*fetch_user_achievements)(struct IDiscordAchievementManager *, void *, void (*)(void *, enum EDiscordResult))
     * }
     */
    public static final long fetch_user_achievements$offset() {
        return fetch_user_achievements$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*fetch_user_achievements)(struct IDiscordAchievementManager *, void *, void (*)(void *, enum EDiscordResult))
     * }
     */
    public static MemorySegment fetch_user_achievements(MemorySegment struct) {
        return struct.get(fetch_user_achievements$LAYOUT, fetch_user_achievements$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*fetch_user_achievements)(struct IDiscordAchievementManager *, void *, void (*)(void *, enum EDiscordResult))
     * }
     */
    public static void fetch_user_achievements(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(fetch_user_achievements$LAYOUT, fetch_user_achievements$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*count_user_achievements)(struct IDiscordAchievementManager *, int32_t *)
     * }
     */
    public static class count_user_achievements {

        count_user_achievements() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout count_user_achievements$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("count_user_achievements"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*count_user_achievements)(struct IDiscordAchievementManager *, int32_t *)
     * }
     */
    public static final AddressLayout count_user_achievements$layout() {
        return count_user_achievements$LAYOUT;
    }

    private static final long count_user_achievements$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*count_user_achievements)(struct IDiscordAchievementManager *, int32_t *)
     * }
     */
    public static final long count_user_achievements$offset() {
        return count_user_achievements$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*count_user_achievements)(struct IDiscordAchievementManager *, int32_t *)
     * }
     */
    public static MemorySegment count_user_achievements(MemorySegment struct) {
        return struct.get(count_user_achievements$LAYOUT, count_user_achievements$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*count_user_achievements)(struct IDiscordAchievementManager *, int32_t *)
     * }
     */
    public static void count_user_achievements(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(count_user_achievements$LAYOUT, count_user_achievements$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * enum EDiscordResult (*get_user_achievement)(struct IDiscordAchievementManager *, DiscordSnowflake, struct DiscordUserAchievement *)
     * }
     */
    public static class get_user_achievement {

        get_user_achievement() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, long _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_INT,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_LONG_LONG,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr,MemorySegment _x0, long _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_user_achievement$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_user_achievement"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*get_user_achievement)(struct IDiscordAchievementManager *, DiscordSnowflake, struct DiscordUserAchievement *)
     * }
     */
    public static final AddressLayout get_user_achievement$layout() {
        return get_user_achievement$LAYOUT;
    }

    private static final long get_user_achievement$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*get_user_achievement)(struct IDiscordAchievementManager *, DiscordSnowflake, struct DiscordUserAchievement *)
     * }
     */
    public static final long get_user_achievement$offset() {
        return get_user_achievement$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*get_user_achievement)(struct IDiscordAchievementManager *, DiscordSnowflake, struct DiscordUserAchievement *)
     * }
     */
    public static MemorySegment get_user_achievement(MemorySegment struct) {
        return struct.get(get_user_achievement$LAYOUT, get_user_achievement$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*get_user_achievement)(struct IDiscordAchievementManager *, DiscordSnowflake, struct DiscordUserAchievement *)
     * }
     */
    public static void get_user_achievement(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_user_achievement$LAYOUT, get_user_achievement$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * enum EDiscordResult (*get_user_achievement_at)(struct IDiscordAchievementManager *, int32_t, struct DiscordUserAchievement *)
     * }
     */
    public static class get_user_achievement_at {

        get_user_achievement_at() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_INT,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_INT,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr,MemorySegment _x0, int _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_user_achievement_at$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_user_achievement_at"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*get_user_achievement_at)(struct IDiscordAchievementManager *, int32_t, struct DiscordUserAchievement *)
     * }
     */
    public static final AddressLayout get_user_achievement_at$layout() {
        return get_user_achievement_at$LAYOUT;
    }

    private static final long get_user_achievement_at$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*get_user_achievement_at)(struct IDiscordAchievementManager *, int32_t, struct DiscordUserAchievement *)
     * }
     */
    public static final long get_user_achievement_at$offset() {
        return get_user_achievement_at$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*get_user_achievement_at)(struct IDiscordAchievementManager *, int32_t, struct DiscordUserAchievement *)
     * }
     */
    public static MemorySegment get_user_achievement_at(MemorySegment struct) {
        return struct.get(get_user_achievement_at$LAYOUT, get_user_achievement_at$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*get_user_achievement_at)(struct IDiscordAchievementManager *, int32_t, struct DiscordUserAchievement *)
     * }
     */
    public static void get_user_achievement_at(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_user_achievement_at$LAYOUT, get_user_achievement_at$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

