package discord.gamesdk;// Generated by jextract

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct IDiscordUserManager {
 *     enum EDiscordResult (*get_current_user)(struct IDiscordUserManager *, struct DiscordUser *);
 *     void (*get_user)(struct IDiscordUserManager *, DiscordUserId, void *, void (*)(void *, enum EDiscordResult, struct DiscordUser *));
 *     enum EDiscordResult (*get_current_user_premium_type)(struct IDiscordUserManager *, enum EDiscordPremiumType *);
 *     enum EDiscordResult (*current_user_has_flag)(struct IDiscordUserManager *, enum EDiscordUserFlag, bool *);
 * }
 * }
 */
public class IDiscordUserManager {

    IDiscordUserManager() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        discord_game_sdk_h.C_POINTER.withName("get_current_user"),
        discord_game_sdk_h.C_POINTER.withName("get_user"),
        discord_game_sdk_h.C_POINTER.withName("get_current_user_premium_type"),
        discord_game_sdk_h.C_POINTER.withName("current_user_has_flag")
    ).withName("IDiscordUserManager");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * {@snippet lang=c :
     * enum EDiscordResult (*get_current_user)(struct IDiscordUserManager *, struct DiscordUser *)
     * }
     */
    public static class get_current_user {

        get_current_user() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_INT,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_current_user$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_current_user"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*get_current_user)(struct IDiscordUserManager *, struct DiscordUser *)
     * }
     */
    public static final AddressLayout get_current_user$layout() {
        return get_current_user$LAYOUT;
    }

    private static final long get_current_user$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*get_current_user)(struct IDiscordUserManager *, struct DiscordUser *)
     * }
     */
    public static final long get_current_user$offset() {
        return get_current_user$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*get_current_user)(struct IDiscordUserManager *, struct DiscordUser *)
     * }
     */
    public static MemorySegment get_current_user(MemorySegment struct) {
        return struct.get(get_current_user$LAYOUT, get_current_user$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*get_current_user)(struct IDiscordUserManager *, struct DiscordUser *)
     * }
     */
    public static void get_current_user(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_current_user$LAYOUT, get_current_user$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*get_user)(struct IDiscordUserManager *, DiscordUserId, void *, void (*)(void *, enum EDiscordResult, struct DiscordUser *))
     * }
     */
    public static class get_user {

        get_user() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, long _x1, MemorySegment _x2, MemorySegment _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_LONG_LONG,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr,MemorySegment _x0, long _x1, MemorySegment _x2, MemorySegment _x3) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_user$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_user"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*get_user)(struct IDiscordUserManager *, DiscordUserId, void *, void (*)(void *, enum EDiscordResult, struct DiscordUser *))
     * }
     */
    public static final AddressLayout get_user$layout() {
        return get_user$LAYOUT;
    }

    private static final long get_user$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*get_user)(struct IDiscordUserManager *, DiscordUserId, void *, void (*)(void *, enum EDiscordResult, struct DiscordUser *))
     * }
     */
    public static final long get_user$offset() {
        return get_user$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*get_user)(struct IDiscordUserManager *, DiscordUserId, void *, void (*)(void *, enum EDiscordResult, struct DiscordUser *))
     * }
     */
    public static MemorySegment get_user(MemorySegment struct) {
        return struct.get(get_user$LAYOUT, get_user$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*get_user)(struct IDiscordUserManager *, DiscordUserId, void *, void (*)(void *, enum EDiscordResult, struct DiscordUser *))
     * }
     */
    public static void get_user(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_user$LAYOUT, get_user$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * enum EDiscordResult (*get_current_user_premium_type)(struct IDiscordUserManager *, enum EDiscordPremiumType *)
     * }
     */
    public static class get_current_user_premium_type {

        get_current_user_premium_type() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_INT,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_current_user_premium_type$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_current_user_premium_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*get_current_user_premium_type)(struct IDiscordUserManager *, enum EDiscordPremiumType *)
     * }
     */
    public static final AddressLayout get_current_user_premium_type$layout() {
        return get_current_user_premium_type$LAYOUT;
    }

    private static final long get_current_user_premium_type$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*get_current_user_premium_type)(struct IDiscordUserManager *, enum EDiscordPremiumType *)
     * }
     */
    public static final long get_current_user_premium_type$offset() {
        return get_current_user_premium_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*get_current_user_premium_type)(struct IDiscordUserManager *, enum EDiscordPremiumType *)
     * }
     */
    public static MemorySegment get_current_user_premium_type(MemorySegment struct) {
        return struct.get(get_current_user_premium_type$LAYOUT, get_current_user_premium_type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*get_current_user_premium_type)(struct IDiscordUserManager *, enum EDiscordPremiumType *)
     * }
     */
    public static void get_current_user_premium_type(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_current_user_premium_type$LAYOUT, get_current_user_premium_type$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * enum EDiscordResult (*current_user_has_flag)(struct IDiscordUserManager *, enum EDiscordUserFlag, bool *)
     * }
     */
    public static class current_user_has_flag {

        current_user_has_flag() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_INT,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_INT,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr,MemorySegment _x0, int _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout current_user_has_flag$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("current_user_has_flag"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*current_user_has_flag)(struct IDiscordUserManager *, enum EDiscordUserFlag, bool *)
     * }
     */
    public static final AddressLayout current_user_has_flag$layout() {
        return current_user_has_flag$LAYOUT;
    }

    private static final long current_user_has_flag$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*current_user_has_flag)(struct IDiscordUserManager *, enum EDiscordUserFlag, bool *)
     * }
     */
    public static final long current_user_has_flag$offset() {
        return current_user_has_flag$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*current_user_has_flag)(struct IDiscordUserManager *, enum EDiscordUserFlag, bool *)
     * }
     */
    public static MemorySegment current_user_has_flag(MemorySegment struct) {
        return struct.get(current_user_has_flag$LAYOUT, current_user_has_flag$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*current_user_has_flag)(struct IDiscordUserManager *, enum EDiscordUserFlag, bool *)
     * }
     */
    public static void current_user_has_flag(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(current_user_has_flag$LAYOUT, current_user_has_flag$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

