package discord.gamesdk;// Generated by jextract

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct IDiscordAchievementEvents {
 *     void (*on_user_achievement_update)(void *, struct DiscordUserAchievement *);
 * }
 * }
 */
public class IDiscordAchievementEvents {

    IDiscordAchievementEvents() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        discord_game_sdk_h.C_POINTER.withName("on_user_achievement_update")
    ).withName("IDiscordAchievementEvents");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * {@snippet lang=c :
     * void (*on_user_achievement_update)(void *, struct DiscordUserAchievement *)
     * }
     */
    public static class on_user_achievement_update {

        on_user_achievement_update() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout on_user_achievement_update$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("on_user_achievement_update"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*on_user_achievement_update)(void *, struct DiscordUserAchievement *)
     * }
     */
    public static final AddressLayout on_user_achievement_update$layout() {
        return on_user_achievement_update$LAYOUT;
    }

    private static final long on_user_achievement_update$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*on_user_achievement_update)(void *, struct DiscordUserAchievement *)
     * }
     */
    public static final long on_user_achievement_update$offset() {
        return on_user_achievement_update$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*on_user_achievement_update)(void *, struct DiscordUserAchievement *)
     * }
     */
    public static MemorySegment on_user_achievement_update(MemorySegment struct) {
        return struct.get(on_user_achievement_update$LAYOUT, on_user_achievement_update$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*on_user_achievement_update)(void *, struct DiscordUserAchievement *)
     * }
     */
    public static void on_user_achievement_update(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(on_user_achievement_update$LAYOUT, on_user_achievement_update$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

