package discord.gamesdk;// Generated by jextract

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct IDiscordStoreEvents {
 *     void (*on_entitlement_create)(void *, struct DiscordEntitlement *);
 *     void (*on_entitlement_delete)(void *, struct DiscordEntitlement *);
 * }
 * }
 */
public class IDiscordStoreEvents {

    IDiscordStoreEvents() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        discord_game_sdk_h.C_POINTER.withName("on_entitlement_create"),
        discord_game_sdk_h.C_POINTER.withName("on_entitlement_delete")
    ).withName("IDiscordStoreEvents");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * {@snippet lang=c :
     * void (*on_entitlement_create)(void *, struct DiscordEntitlement *)
     * }
     */
    public static class on_entitlement_create {

        on_entitlement_create() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout on_entitlement_create$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("on_entitlement_create"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*on_entitlement_create)(void *, struct DiscordEntitlement *)
     * }
     */
    public static final AddressLayout on_entitlement_create$layout() {
        return on_entitlement_create$LAYOUT;
    }

    private static final long on_entitlement_create$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*on_entitlement_create)(void *, struct DiscordEntitlement *)
     * }
     */
    public static final long on_entitlement_create$offset() {
        return on_entitlement_create$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*on_entitlement_create)(void *, struct DiscordEntitlement *)
     * }
     */
    public static MemorySegment on_entitlement_create(MemorySegment struct) {
        return struct.get(on_entitlement_create$LAYOUT, on_entitlement_create$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*on_entitlement_create)(void *, struct DiscordEntitlement *)
     * }
     */
    public static void on_entitlement_create(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(on_entitlement_create$LAYOUT, on_entitlement_create$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*on_entitlement_delete)(void *, struct DiscordEntitlement *)
     * }
     */
    public static class on_entitlement_delete {

        on_entitlement_delete() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout on_entitlement_delete$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("on_entitlement_delete"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*on_entitlement_delete)(void *, struct DiscordEntitlement *)
     * }
     */
    public static final AddressLayout on_entitlement_delete$layout() {
        return on_entitlement_delete$LAYOUT;
    }

    private static final long on_entitlement_delete$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*on_entitlement_delete)(void *, struct DiscordEntitlement *)
     * }
     */
    public static final long on_entitlement_delete$offset() {
        return on_entitlement_delete$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*on_entitlement_delete)(void *, struct DiscordEntitlement *)
     * }
     */
    public static MemorySegment on_entitlement_delete(MemorySegment struct) {
        return struct.get(on_entitlement_delete$LAYOUT, on_entitlement_delete$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*on_entitlement_delete)(void *, struct DiscordEntitlement *)
     * }
     */
    public static void on_entitlement_delete(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(on_entitlement_delete$LAYOUT, on_entitlement_delete$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

