package discord.gamesdk;// Generated by jextract

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct IDiscordLobbySearchQuery {
 *     enum EDiscordResult (*filter)(struct IDiscordLobbySearchQuery *, char *, enum EDiscordLobbySearchComparison, enum EDiscordLobbySearchCast, char *);
 *     enum EDiscordResult (*sort)(struct IDiscordLobbySearchQuery *, char *, enum EDiscordLobbySearchCast, char *);
 *     enum EDiscordResult (*limit)(struct IDiscordLobbySearchQuery *, uint32_t);
 *     enum EDiscordResult (*distance)(struct IDiscordLobbySearchQuery *, enum EDiscordLobbySearchDistance);
 * }
 * }
 */
public class IDiscordLobbySearchQuery {

    IDiscordLobbySearchQuery() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        discord_game_sdk_h.C_POINTER.withName("filter"),
        discord_game_sdk_h.C_POINTER.withName("sort"),
        discord_game_sdk_h.C_POINTER.withName("limit"),
        discord_game_sdk_h.C_POINTER.withName("distance")
    ).withName("IDiscordLobbySearchQuery");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * {@snippet lang=c :
     * enum EDiscordResult (*filter)(struct IDiscordLobbySearchQuery *, char *, enum EDiscordLobbySearchComparison, enum EDiscordLobbySearchCast, char *)
     * }
     */
    public static class filter {

        filter() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1, int _x2, int _x3, MemorySegment _x4);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_INT,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_INT,
            discord_game_sdk_h.C_INT,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1, int _x2, int _x3, MemorySegment _x4) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout filter$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("filter"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*filter)(struct IDiscordLobbySearchQuery *, char *, enum EDiscordLobbySearchComparison, enum EDiscordLobbySearchCast, char *)
     * }
     */
    public static final AddressLayout filter$layout() {
        return filter$LAYOUT;
    }

    private static final long filter$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*filter)(struct IDiscordLobbySearchQuery *, char *, enum EDiscordLobbySearchComparison, enum EDiscordLobbySearchCast, char *)
     * }
     */
    public static final long filter$offset() {
        return filter$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*filter)(struct IDiscordLobbySearchQuery *, char *, enum EDiscordLobbySearchComparison, enum EDiscordLobbySearchCast, char *)
     * }
     */
    public static MemorySegment filter(MemorySegment struct) {
        return struct.get(filter$LAYOUT, filter$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*filter)(struct IDiscordLobbySearchQuery *, char *, enum EDiscordLobbySearchComparison, enum EDiscordLobbySearchCast, char *)
     * }
     */
    public static void filter(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(filter$LAYOUT, filter$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * enum EDiscordResult (*sort)(struct IDiscordLobbySearchQuery *, char *, enum EDiscordLobbySearchCast, char *)
     * }
     */
    public static class sort {

        sort() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1, int _x2, MemorySegment _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_INT,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_INT,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1, int _x2, MemorySegment _x3) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout sort$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("sort"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*sort)(struct IDiscordLobbySearchQuery *, char *, enum EDiscordLobbySearchCast, char *)
     * }
     */
    public static final AddressLayout sort$layout() {
        return sort$LAYOUT;
    }

    private static final long sort$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*sort)(struct IDiscordLobbySearchQuery *, char *, enum EDiscordLobbySearchCast, char *)
     * }
     */
    public static final long sort$offset() {
        return sort$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*sort)(struct IDiscordLobbySearchQuery *, char *, enum EDiscordLobbySearchCast, char *)
     * }
     */
    public static MemorySegment sort(MemorySegment struct) {
        return struct.get(sort$LAYOUT, sort$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*sort)(struct IDiscordLobbySearchQuery *, char *, enum EDiscordLobbySearchCast, char *)
     * }
     */
    public static void sort(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(sort$LAYOUT, sort$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * enum EDiscordResult (*limit)(struct IDiscordLobbySearchQuery *, uint32_t)
     * }
     */
    public static class limit {

        limit() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_INT,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr,MemorySegment _x0, int _x1) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout limit$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("limit"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*limit)(struct IDiscordLobbySearchQuery *, uint32_t)
     * }
     */
    public static final AddressLayout limit$layout() {
        return limit$LAYOUT;
    }

    private static final long limit$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*limit)(struct IDiscordLobbySearchQuery *, uint32_t)
     * }
     */
    public static final long limit$offset() {
        return limit$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*limit)(struct IDiscordLobbySearchQuery *, uint32_t)
     * }
     */
    public static MemorySegment limit(MemorySegment struct) {
        return struct.get(limit$LAYOUT, limit$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*limit)(struct IDiscordLobbySearchQuery *, uint32_t)
     * }
     */
    public static void limit(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(limit$LAYOUT, limit$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * enum EDiscordResult (*distance)(struct IDiscordLobbySearchQuery *, enum EDiscordLobbySearchDistance)
     * }
     */
    public static class distance {

        distance() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_INT,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr,MemorySegment _x0, int _x1) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout distance$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("distance"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*distance)(struct IDiscordLobbySearchQuery *, enum EDiscordLobbySearchDistance)
     * }
     */
    public static final AddressLayout distance$layout() {
        return distance$LAYOUT;
    }

    private static final long distance$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*distance)(struct IDiscordLobbySearchQuery *, enum EDiscordLobbySearchDistance)
     * }
     */
    public static final long distance$offset() {
        return distance$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*distance)(struct IDiscordLobbySearchQuery *, enum EDiscordLobbySearchDistance)
     * }
     */
    public static MemorySegment distance(MemorySegment struct) {
        return struct.get(distance$LAYOUT, distance$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*distance)(struct IDiscordLobbySearchQuery *, enum EDiscordLobbySearchDistance)
     * }
     */
    public static void distance(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(distance$LAYOUT, distance$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

