package discord.gamesdk;// Generated by jextract

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct IDiscordLobbyMemberTransaction {
 *     enum EDiscordResult (*set_metadata)(struct IDiscordLobbyMemberTransaction *, char *, char *);
 *     enum EDiscordResult (*delete_metadata)(struct IDiscordLobbyMemberTransaction *, char *);
 * }
 * }
 */
public class IDiscordLobbyMemberTransaction {

    IDiscordLobbyMemberTransaction() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        discord_game_sdk_h.C_POINTER.withName("set_metadata"),
        discord_game_sdk_h.C_POINTER.withName("delete_metadata")
    ).withName("IDiscordLobbyMemberTransaction");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * {@snippet lang=c :
     * enum EDiscordResult (*set_metadata)(struct IDiscordLobbyMemberTransaction *, char *, char *)
     * }
     */
    public static class set_metadata {

        set_metadata() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_INT,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout set_metadata$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("set_metadata"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*set_metadata)(struct IDiscordLobbyMemberTransaction *, char *, char *)
     * }
     */
    public static final AddressLayout set_metadata$layout() {
        return set_metadata$LAYOUT;
    }

    private static final long set_metadata$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*set_metadata)(struct IDiscordLobbyMemberTransaction *, char *, char *)
     * }
     */
    public static final long set_metadata$offset() {
        return set_metadata$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*set_metadata)(struct IDiscordLobbyMemberTransaction *, char *, char *)
     * }
     */
    public static MemorySegment set_metadata(MemorySegment struct) {
        return struct.get(set_metadata$LAYOUT, set_metadata$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*set_metadata)(struct IDiscordLobbyMemberTransaction *, char *, char *)
     * }
     */
    public static void set_metadata(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(set_metadata$LAYOUT, set_metadata$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * enum EDiscordResult (*delete_metadata)(struct IDiscordLobbyMemberTransaction *, char *)
     * }
     */
    public static class delete_metadata {

        delete_metadata() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            discord_game_sdk_h.C_INT,
            discord_game_sdk_h.C_POINTER,
            discord_game_sdk_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = discord_game_sdk_h.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout delete_metadata$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("delete_metadata"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*delete_metadata)(struct IDiscordLobbyMemberTransaction *, char *)
     * }
     */
    public static final AddressLayout delete_metadata$layout() {
        return delete_metadata$LAYOUT;
    }

    private static final long delete_metadata$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*delete_metadata)(struct IDiscordLobbyMemberTransaction *, char *)
     * }
     */
    public static final long delete_metadata$offset() {
        return delete_metadata$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*delete_metadata)(struct IDiscordLobbyMemberTransaction *, char *)
     * }
     */
    public static MemorySegment delete_metadata(MemorySegment struct) {
        return struct.get(delete_metadata$LAYOUT, delete_metadata$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum EDiscordResult (*delete_metadata)(struct IDiscordLobbyMemberTransaction *, char *)
     * }
     */
    public static void delete_metadata(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(delete_metadata$LAYOUT, delete_metadata$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

